//! no_std Rust client-catalog generation.

use anyhow::{Result, bail};
use convert_case::{Case, Casing};
use std::fmt::Write;

use super::{module_for_trait, wire_method_name, wire_table::infer_id};
use crate::rustdoc::{ApiDefinition, MethodDef, MethodKind, ReturnType, TraitDef, TypeRef};

pub fn generate_client(api: &ApiDefinition, schema_hash: &str) -> Result<String> {
    let mut out = String::new();
    writeln!(out, "//! Canonical TrUAPI client method catalog.")?;
    writeln!(out, "//!")?;
    writeln!(out, "//! Auto-generated by truapi-codegen. Do not edit.\n")?;
    writeln!(out, "use super::*;\n")?;
    writeln!(out, "/// Fingerprint of the generated wire contract.")?;
    writeln!(
        out,
        "pub const TRUAPI_WIRE_SCHEMA_HASH: &str = \"{schema_hash}\";\n"
    )?;

    let mut app = Vec::new();
    let mut widget = Vec::new();
    let mut worker = Vec::new();
    let mut worker_only = Vec::new();

    for trait_name in &api.public_trait_order {
        let service = api
            .traits
            .iter()
            .find(|candidate| candidate.name == *trait_name)
            .ok_or_else(|| anyhow::anyhow!("public trait `{trait_name}` was not extracted"))?;
        let requirement = execution_requirement(service)?;
        for method in &service.methods {
            let marker = marker_name(service, method);
            emit_method(&mut out, service, method, requirement, &marker)?;
            match requirement {
                None => {
                    app.push(marker.clone());
                    widget.push(marker.clone());
                    worker.push(marker);
                }
                Some("App") => app.push(marker),
                Some("Widget") => widget.push(marker),
                Some("Worker") => {
                    worker.push(marker.clone());
                    worker_only.push(marker);
                }
                Some(other) => bail!("unsupported execution requirement `{other}`"),
            }
        }
    }

    emit_catalog(&mut out, "APP_METHODS", &app)?;
    emit_catalog(&mut out, "WIDGET_METHODS", &widget)?;
    emit_catalog(&mut out, "WORKER_METHODS", &worker)?;
    emit_catalog(&mut out, "WORKER_ONLY_METHODS", &worker_only)?;
    Ok(out)
}

fn execution_requirement(service: &TraitDef) -> Result<Option<&str>> {
    let requirement = service.required_execution();
    if let Some(value) = requirement
        && !matches!(value, "App" | "Widget" | "Worker")
    {
        bail!(
            "service `{}` has unknown execution requirement `{value}`",
            service.name
        );
    }
    Ok(requirement)
}

fn marker_name(service: &TraitDef, method: &MethodDef) -> String {
    format!("{}_{}", service.name, method.name).to_case(Case::Pascal)
}

fn emit_method(
    out: &mut String,
    service: &TraitDef,
    method: &MethodDef,
    requirement: Option<&str>,
    marker: &str,
) -> Result<()> {
    let module = module_for_trait(&service.name);
    let wire_name = wire_method_name(&service.name, &method.name);
    let execution = requirement
        .map(|value| format!("Some(ExecutionKind::{value})"))
        .unwrap_or_else(|| "None".to_string());
    let direction = if method.wire.host_initiated {
        "Direction::HostToProduct"
    } else {
        "Direction::ProductToHost"
    };
    let kind = match method.kind {
        MethodKind::Request => "MethodKind::Request",
        MethodKind::Subscription => "MethodKind::Subscription",
        MethodKind::ResultSubscription => "MethodKind::ResultSubscription",
    };
    let wire = match method.kind {
        MethodKind::Request => {
            let request_id = method
                .wire
                .request_id
                .ok_or_else(|| anyhow::anyhow!("method `{wire_name}` is missing request_id"))?;
            let response_id = infer_id(method.wire.response_id, request_id, 1, &wire_name)?;
            format!(
                "MethodWire::Request(RequestFrameIds {{ request_id: {request_id}, response_id: {response_id} }})"
            )
        }
        MethodKind::Subscription | MethodKind::ResultSubscription => {
            let start_id = method
                .wire
                .start_id
                .ok_or_else(|| anyhow::anyhow!("method `{wire_name}` is missing start_id"))?;
            let stop_id = infer_id(method.wire.stop_id, start_id, 1, &wire_name)?;
            let interrupt_id = infer_id(method.wire.interrupt_id, start_id, 2, &wire_name)?;
            let receive_id = infer_id(method.wire.receive_id, start_id, 3, &wire_name)?;
            format!(
                "MethodWire::Subscription(SubscriptionFrameIds {{ start_id: {start_id}, stop_id: {stop_id}, interrupt_id: {interrupt_id}, receive_id: {receive_id} }})"
            )
        }
    };
    let request_name = request_type(method, &module)?;
    let (response_name, error_name) = match &method.return_type {
        ReturnType::Result { ok, err } => (
            rust_type(ok, &module)?,
            Some(rust_type(call_error_domain(err)?, &module)?),
        ),
        ReturnType::Subscription(item) => (rust_type(item, &module)?, None),
        ReturnType::ResultSubscription { item, err } => (
            rust_type(item, &module)?,
            Some(rust_type(call_error_domain(err)?, &module)?),
        ),
    };

    writeln!(out, "/// `{wire_name}` method marker.")?;
    writeln!(out, "pub struct {marker};")?;
    writeln!(out, "impl {marker} {{")?;
    writeln!(
        out,
        "    /// Canonical metadata and frame ids for this method."
    )?;
    writeln!(
        out,
        "    pub const DESCRIPTOR: MethodDescriptor = MethodDescriptor {{"
    )?;
    writeln!(out, "        service: \"{}\",", service.name)?;
    writeln!(out, "        method: \"{}\",", method.name)?;
    writeln!(out, "        wire_name: \"{wire_name}\",")?;
    writeln!(out, "        request_type: \"{request_name}\",")?;
    writeln!(out, "        response_type: \"{response_name}\",")?;
    match error_name {
        Some(error) => writeln!(out, "        error_type: Some(\"{error}\"),")?,
        None => writeln!(out, "        error_type: None,")?,
    }
    writeln!(out, "        kind: {kind},")?;
    writeln!(out, "        direction: {direction},")?;
    writeln!(out, "        required_execution: {execution},")?;
    writeln!(out, "        sensitive: {},", method.wire.sensitive)?;
    writeln!(out, "        wire: {wire},")?;
    writeln!(out, "    }};")?;
    writeln!(out, "}}")?;

    let request = request_type(method, &module)?;
    match (
        &method.kind,
        &method.return_type,
        method.wire.host_initiated,
    ) {
        (MethodKind::Request, ReturnType::Result { ok, err }, false) => {
            let response = rust_type(ok, &module)?;
            let error = rust_type(call_error_domain(err)?, &module)?;
            writeln!(out, "impl RequestMethod for {marker} {{")?;
            writeln!(out, "    type Request = {request};")?;
            writeln!(out, "    type Response = {response};")?;
            writeln!(out, "    type Error = {error};")?;
            writeln!(
                out,
                "    const RESPONSE_VERSIONED: bool = {};",
                !matches!(ok, TypeRef::Unit)
            )?;
            writeln!(
                out,
                "    const DESCRIPTOR: MethodDescriptor = Self::DESCRIPTOR;"
            )?;
            writeln!(out, "}}\n")?;
        }
        (MethodKind::Subscription, ReturnType::Subscription(item), false) => {
            let item = rust_type(item, &module)?;
            writeln!(out, "impl SubscriptionMethod for {marker} {{")?;
            writeln!(out, "    type Request = {request};")?;
            writeln!(out, "    type Item = {item};")?;
            writeln!(
                out,
                "    const DESCRIPTOR: MethodDescriptor = Self::DESCRIPTOR;"
            )?;
            writeln!(out, "}}\n")?;
        }
        (MethodKind::ResultSubscription, ReturnType::ResultSubscription { item, err }, false) => {
            let item = rust_type(item, &module)?;
            let error = rust_type(call_error_domain(err)?, &module)?;
            writeln!(out, "impl ResultSubscriptionMethod for {marker} {{")?;
            writeln!(out, "    type Request = {request};")?;
            writeln!(out, "    type Item = {item};")?;
            writeln!(out, "    type Error = {error};")?;
            writeln!(
                out,
                "    const DESCRIPTOR: MethodDescriptor = Self::DESCRIPTOR;"
            )?;
            writeln!(out, "}}\n")?;
        }
        (MethodKind::Subscription, ReturnType::Subscription(item), true) => {
            let item = rust_type(item, &module)?;
            writeln!(out, "impl HostSubscriptionMethod for {marker} {{")?;
            writeln!(out, "    type Request = {request};")?;
            writeln!(out, "    type Item = {item};")?;
            writeln!(
                out,
                "    const DESCRIPTOR: MethodDescriptor = Self::DESCRIPTOR;"
            )?;
            writeln!(out, "}}\n")?;
        }
        _ => bail!("method `{wire_name}` has unsupported kind/return/direction combination"),
    }
    Ok(())
}

fn request_type(method: &MethodDef, module: &str) -> Result<String> {
    match method.params.as_slice() {
        [] => Ok("()".to_string()),
        [param] => rust_type(&param.type_ref, module),
        params => bail!(
            "method `{}` has {} wire parameters; expected at most one request wrapper",
            method.name,
            params.len()
        ),
    }
}

fn call_error_domain(error: &TypeRef) -> Result<&TypeRef> {
    match error {
        TypeRef::Named { name, args } if name == "CallError" && args.len() == 1 => Ok(&args[0]),
        _ => bail!("method error is not CallError<Domain>: {error:?}"),
    }
}

fn rust_type(value: &TypeRef, module: &str) -> Result<String> {
    Ok(match value {
        TypeRef::Primitive(name) if name == "String" => "alloc::string::String".to_string(),
        TypeRef::Primitive(name) => name.clone(),
        TypeRef::Named { name, args } if name == "String" && args.is_empty() => {
            "alloc::string::String".to_string()
        }
        TypeRef::Named { name, args } if name == "Vec" && args.len() == 1 => {
            format!("alloc::vec::Vec<{}>", rust_type(&args[0], module)?)
        }
        TypeRef::Named { name, args } if name == "Option" && args.len() == 1 => {
            format!("Option<{}>", rust_type(&args[0], module)?)
        }
        TypeRef::Named { name, args } if name == "Infallible" && args.is_empty() => {
            "core::convert::Infallible".to_string()
        }
        TypeRef::Named { name, args } if args.is_empty() => {
            format!("truapi::versioned::{module}::{name}")
        }
        TypeRef::Named { name, args } => {
            let args = args
                .iter()
                .map(|arg| rust_type(arg, module))
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            format!("truapi::versioned::{module}::{name}<{args}>")
        }
        TypeRef::Vec(inner) => format!("alloc::vec::Vec<{}>", rust_type(inner, module)?),
        TypeRef::Option(inner) => format!("Option<{}>", rust_type(inner, module)?),
        TypeRef::Tuple(items) => {
            let mut rendered = items
                .iter()
                .map(|item| rust_type(item, module))
                .collect::<Result<Vec<_>>>()?
                .join(", ");
            if items.len() == 1 {
                rendered.push(',');
            }
            format!("({rendered})")
        }
        TypeRef::Array(inner, len) => format!("[{}; {len}]", rust_type(inner, module)?),
        TypeRef::Generic(name) => bail!("unresolved generic type `{name}` in method surface"),
        TypeRef::Unit => "()".to_string(),
    })
}

fn emit_catalog(out: &mut String, name: &str, markers: &[String]) -> Result<()> {
    writeln!(out, "/// Generated `{name}` execution catalog.")?;
    writeln!(out, "pub const {name}: &[MethodDescriptor] = &[")?;
    for marker in markers {
        writeln!(out, "    {marker}::DESCRIPTOR,")?;
    }
    writeln!(out, "];\n")?;
    Ok(())
}
