//! Versioned request and response wrappers for the unified TrUAPI contract.
//!
//! A versioned envelope is a SCALE enum whose variants (`V1`, `V2`, ...) are
//! successive versions of one logical message, newest last. A server normalizes
//! incoming values to [`Versioned::Latest`] with [`IntoLatest`], handles them in
//! latest terms, then maps results back to the caller's version with
//! [`FromLatest`]. The envelopes themselves are generated by `versioned_type!`,
//! and each variant wraps either `Request` or `Subscription` rather than a bare
//! payload: version selects a method's shape, direction is carried inside that
//! version's payload rather than addressed by a separate wire id.

use parity_scale_codec::{Decode, Encode};

/// A versioned message envelope.
pub trait Versioned: Sized {
    /// The newest version's payload. Handlers operate exclusively on this.
    type Latest;

    /// Version number of the newest variant.
    const LATEST: u8;

    /// Version number of the variant currently held.
    fn version(&self) -> u8;
}

/// Upgrade a received envelope to its latest payload. Total by construction.
pub trait IntoLatest: Versioned {
    /// Convert whatever version is held into the latest payload.
    fn into_latest(self) -> Self::Latest;
}

/// Downgrade a latest payload into the variant a peer at `target` understands.
pub trait FromLatest: Versioned {
    /// Build the envelope for protocol version `target` (highest variant ≤ target).
    fn from_latest(latest: Self::Latest, target: u8) -> Self;
}

/// Direction tag for a request/response method: which half of the exchange
/// this frame carries. Wrapped inside a method's version enum, so a method's
/// version history is the one place its shape can change.
// Not yet referenced outside this module's own tests: the generated code that
// wraps every method's version enum in this lands in a separate stacked PR.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub(crate) enum Request<Req, Res> {
    /// Product-to-host call.
    Request(Req),
    /// Host-to-product reply.
    Response(Res),
}

/// Direction tag for a subscription method: which half of the four-frame
/// exchange this frame carries. `Start` and `Receive` lead, in the same
/// position as [`Request`]'s own two variants, so subscription decoding is
/// partly shape-compatible with request decoding. `Stop` carries no payload;
/// `Interrupt` carries `None` for natural stream completion or `Some(err)`
/// for a failure.
#[allow(dead_code)]
#[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
pub(crate) enum Subscription<Start, Item, Err> {
    /// Product-to-host subscription request.
    Start(Start),
    /// Host-to-product streamed item.
    Receive(Item),
    /// Host-to-product termination: `None` on clean completion, `Some` on failure.
    Interrupt(Option<Err>),
    /// Product-to-host cancellation.
    Stop,
}

pub mod account;
pub mod chain;
pub mod chat;
pub mod coin_payment;
pub mod entropy;
pub mod local_storage;
pub mod locale;
pub mod notifications;
pub mod payment;
pub mod permissions;
pub mod preimage;
pub mod resource_allocation;
pub mod signing;
pub mod statement_store;
pub mod system;
pub mod theme;

#[cfg(test)]
mod tests {
    use parity_scale_codec::{Decode, Encode};

    #[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
    struct ProbeV1 {
        a: u32,
    }

    #[derive(Debug, Clone, PartialEq, Eq, Encode, Decode)]
    struct ProbeV2 {
        b: Vec<u8>,
    }

    truapi_macros::versioned_type! {
        enum MultiVersionProbe {
            V1 => ProbeV1,
            V2 => ProbeV2,
        }
    }

    // Multi-version envelopes assign positional SCALE codec indices (V1 -> 0,
    // V2 -> 1) and 1-based version numbers.
    #[test]
    fn multi_version_codec_indices_are_positional() {
        use super::Versioned;

        let v1 = MultiVersionProbe::V1(ProbeV1 { a: 7 });
        let v2 = MultiVersionProbe::V2(ProbeV2 {
            b: b"hello".to_vec(),
        });

        assert_eq!(v1.encode()[0], 0, "V1 encodes codec index 0");
        assert_eq!(v2.encode()[0], 1, "V2 encodes codec index 1");
        assert_eq!(v1.version(), 1);
        assert_eq!(v2.version(), 2);
        assert_eq!(MultiVersionProbe::LATEST, 2);
    }

    #[test]
    fn v1_discriminant_is_zero() {
        let v1 = super::permissions::HostDevicePermissionRequest::V1(
            crate::v01::HostDevicePermissionRequest::Camera,
        );
        assert_eq!(v1.encode()[0], 0, "V1 must encode discriminant 0");
    }

    #[test]
    fn unit_response_roundtrip() {
        let original = super::system::HostNavigateToResponse::V1;
        let decoded = super::system::HostNavigateToResponse::decode(&mut &original.encode()[..])
            .expect("decode");
        assert_eq!(original, decoded);
    }

    #[test]
    fn struct_variant_roundtrip() {
        let original = super::local_storage::HostLocalStorageWriteRequest::V1(
            crate::v01::HostLocalStorageWriteRequest {
                key: "greeting".into(),
                value: b"hello".to_vec(),
            },
        );
        let decoded =
            super::local_storage::HostLocalStorageWriteRequest::decode(&mut &original.encode()[..])
                .expect("decode");
        assert_eq!(original, decoded);
    }

    #[test]
    fn request_direction_tag_roundtrips_both_variants() {
        use super::Request;

        let request = Request::<u32, String>::Request(7);
        let decoded = Request::<u32, String>::decode(&mut &request.encode()[..]).expect("decode");
        assert_eq!(request, decoded);
        assert_eq!(request.encode()[0], 0, "Request must encode discriminant 0");

        let response = Request::<u32, String>::Response("ok".to_string());
        let decoded = Request::<u32, String>::decode(&mut &response.encode()[..]).expect("decode");
        assert_eq!(response, decoded);
        assert_eq!(
            response.encode()[0],
            1,
            "Response must encode discriminant 1"
        );
    }

    #[test]
    fn subscription_direction_tag_roundtrips_every_variant() {
        use super::Subscription;

        let start = Subscription::<u32, String, String>::Start(7);
        assert_eq!(start.encode()[0], 0, "Start must encode discriminant 0");
        assert_eq!(
            Subscription::<u32, String, String>::decode(&mut &start.encode()[..]).expect("decode"),
            start
        );

        let stop = Subscription::<u32, String, String>::Stop;
        assert_eq!(stop.encode()[0], 3, "Stop must encode discriminant 3");
        assert_eq!(
            Subscription::<u32, String, String>::decode(&mut &stop.encode()[..]).expect("decode"),
            stop
        );

        let clean_end = Subscription::<u32, String, String>::Interrupt(None);
        assert_eq!(
            clean_end.encode()[0],
            2,
            "Interrupt must encode discriminant 2"
        );
        assert_eq!(
            Subscription::<u32, String, String>::decode(&mut &clean_end.encode()[..])
                .expect("decode"),
            clean_end
        );

        let failed = Subscription::<u32, String, String>::Interrupt(Some("boom".to_string()));
        assert_eq!(
            Subscription::<u32, String, String>::decode(&mut &failed.encode()[..]).expect("decode"),
            failed
        );

        let item = Subscription::<u32, String, String>::Receive("hello".to_string());
        assert_eq!(item.encode()[0], 1, "Receive must encode discriminant 1");
        assert_eq!(
            Subscription::<u32, String, String>::decode(&mut &item.encode()[..]).expect("decode"),
            item
        );
    }
}
