//! Data-access objects: SQL-annotated trait methods turned into `rusqlite`
//! calls, plus an async twin that takes its connection from the core `Db`.

use std::collections::BTreeSet;

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::{format_ident, quote};
use syn::spanned::Spanned;
use syn::{
    Attribute, Error, FnArg, GenericArgument, Ident, ItemTrait, LitStr, Pat, PathArguments,
    ReturnType, TraitItem, TraitItemFn, Type, parse_macro_input,
};

/// What a method does, from its marker attribute.
enum Kind {
    /// `#[query("…")]`: reads rows.
    Query { sql: LitStr, rows: Rows },
    /// `#[execute("…")]`: changes rows.
    Execute { sql: LitStr, outcome: Outcome },
    /// `#[transaction]`: a body over the other methods, run as one write.
    Transaction,
}

/// How many rows a query returns, from its declared return type.
enum Rows {
    /// `Vec<T>`: every row.
    Many(Box<Type>),
    /// `Option<T>`: the first row, if any.
    Optional(Box<Type>),
    /// `T`: the first row, which must exist.
    One(Box<Type>),
}

/// What an execute returns, from its declared return type.
enum Outcome {
    /// `usize`: rows changed.
    Changed,
    /// `()`: nothing.
    Nothing,
    /// `i64`: the rowid of the last insert.
    InsertId,
}

struct Argument {
    name: Ident,
    ty: Type,
}

struct Method {
    function: TraitItemFn,
    kind: Kind,
    arguments: Vec<Argument>,
    value: Type,
}

/// Parse the macro input and emit generated code or a compiler diagnostic.
pub(super) fn expand(args: TokenStream, item: TokenStream) -> TokenStream {
    if !args.is_empty() {
        let args = TokenStream2::from(args);
        return Error::new(args.span(), "#[dao] takes no arguments")
            .to_compile_error()
            .into();
    }
    let item = parse_macro_input!(item as ItemTrait);
    expand_trait(item)
        .unwrap_or_else(Error::into_compile_error)
        .into()
}

fn expand_trait(mut item: ItemTrait) -> syn::Result<TokenStream2> {
    let mut methods = Vec::new();
    for trait_item in &mut item.items {
        let TraitItem::Fn(function) = trait_item else {
            return Err(Error::new(
                trait_item.span(),
                "a #[dao] trait holds only methods",
            ));
        };
        methods.push(Method::parse(function)?);
    }

    let trait_ident = &item.ident;
    let vis = &item.vis;
    let db_ident = format_ident!("{trait_ident}Db");
    let sync_methods = methods.iter().filter_map(Method::sync_impl);
    let async_methods = methods
        .iter()
        .map(|method| method.async_impl(trait_ident, vis));
    let queries = methods.iter().filter_map(Method::sql);
    let doc = format!(
        "Async [`{trait_ident}`]: each call takes a connection from the database \
         and runs in its own transaction. Generated by `#[dao]`."
    );

    Ok(quote! {
        #item

        impl #trait_ident for ::rusqlite::Connection {
            #(#sync_methods)*
        }

        #[doc = #doc]
        #[derive(Clone)]
        #vis struct #db_ident {
            db: crate::store::Db,
        }

        #[allow(
            dead_code,
            reason = "every DAO method gets an async twin whether or not it is called"
        )]
        impl #db_ident {
            /// Every statement this DAO runs, for checking against the schema.
            #vis const QUERIES: &'static [&'static str] = &[#(#queries),*];

            /// Serves this DAO from `db`.
            #vis fn new(db: crate::store::Db) -> Self {
                Self { db }
            }

            #(#async_methods)*
        }
    })
}

impl Method {
    fn parse(function: &mut TraitItemFn) -> syn::Result<Self> {
        let marker = take_marker(&mut function.attrs, &function.sig.ident)?;
        let arguments = arguments(function)?;
        let value = rusqlite_result_value(&function.sig.output)?;
        let kind = match marker {
            Marker::Query(sql) => {
                reject_body(function, "#[query]")?;
                check_parameters(&sql, &arguments)?;
                Kind::Query {
                    rows: rows(&value),
                    sql,
                }
            }
            Marker::Execute(sql) => {
                reject_body(function, "#[execute]")?;
                check_parameters(&sql, &arguments)?;
                Kind::Execute {
                    outcome: outcome(&value)?,
                    sql,
                }
            }
            Marker::Transaction => {
                if function.default.is_none() {
                    return Err(Error::new(
                        function.sig.span(),
                        "a #[transaction] method needs a body; it runs as one write",
                    ));
                }
                Kind::Transaction
            }
        };
        Ok(Self {
            function: function.clone(),
            kind,
            arguments,
            value,
        })
    }

    fn sql(&self) -> Option<&LitStr> {
        match &self.kind {
            Kind::Query { sql, .. } | Kind::Execute { sql, .. } => Some(sql),
            Kind::Transaction => None,
        }
    }

    /// The `rusqlite::Connection` implementation. Transactions keep the
    /// trait's own default body.
    fn sync_impl(&self) -> Option<TokenStream2> {
        let sig = &self.function.sig;
        let keys: Vec<LitStr> = self
            .arguments
            .iter()
            .map(|argument| LitStr::new(&format!(":{}", argument.name), argument.name.span()))
            .collect();
        let names: Vec<&Ident> = self
            .arguments
            .iter()
            .map(|argument| &argument.name)
            .collect();
        let prepare = |sql: &LitStr| {
            quote! {
                let mut statement = self.prepare_cached(#sql)?;
                let params = ::rusqlite::named_params! { #(#keys: #names),* };
            }
        };
        let body = match &self.kind {
            Kind::Query { sql, rows } => {
                let prepare = prepare(sql);
                let read = match rows {
                    Rows::Many(row) => quote! {
                        ::serde_rusqlite::from_rows::<#row>(statement.query(params)?)
                            .collect::<::core::result::Result<::std::vec::Vec<#row>, _>>()
                            .map_err(crate::store::dao_decode_error)
                    },
                    Rows::Optional(row) => quote! {
                        let mut rows = statement.query(params)?;
                        match rows.next()? {
                            ::core::option::Option::Some(row) => ::serde_rusqlite::from_row::<#row>(row)
                                .map(::core::option::Option::Some)
                                .map_err(crate::store::dao_decode_error),
                            ::core::option::Option::None => ::core::result::Result::Ok(::core::option::Option::None),
                        }
                    },
                    Rows::One(row) => quote! {
                        let mut rows = statement.query(params)?;
                        match rows.next()? {
                            ::core::option::Option::Some(row) => ::serde_rusqlite::from_row::<#row>(row)
                                .map_err(crate::store::dao_decode_error),
                            ::core::option::Option::None => ::core::result::Result::Err(::rusqlite::Error::QueryReturnedNoRows),
                        }
                    },
                };
                quote! { #prepare #read }
            }
            Kind::Execute { sql, outcome } => {
                let prepare = prepare(sql);
                let run = match outcome {
                    Outcome::Changed => quote! { statement.execute(params) },
                    Outcome::Nothing => quote! { statement.execute(params).map(|_| ()) },
                    Outcome::InsertId => quote! {
                        statement.execute(params)?;
                        ::core::result::Result::Ok(self.last_insert_rowid())
                    },
                };
                quote! { #prepare #run }
            }
            Kind::Transaction => return None,
        };
        Some(quote! {
            #sig {
                #body
            }
        })
    }

    /// The async twin on the generated `…Db` struct.
    fn async_impl(&self, trait_ident: &Ident, vis: &syn::Visibility) -> TokenStream2 {
        let name = &self.function.sig.ident;
        let docs = self
            .function
            .attrs
            .iter()
            .filter(|attribute| attribute.path().is_ident("doc"));
        let value = &self.value;
        let parameters = self
            .arguments
            .iter()
            .map(|Argument { name, ty }| quote!(#name: #ty));
        let owned = self.arguments.iter().filter(|argument| is_reference(&argument.ty)).map(
            |Argument { name, .. }| quote!(let #name = ::std::borrow::ToOwned::to_owned(#name);),
        );
        let call = self.arguments.iter().map(|Argument { name, ty }| {
            if is_reference(ty) {
                quote!(::std::borrow::Borrow::borrow(&#name))
            } else {
                quote!(#name)
            }
        });
        let access = match self.kind {
            Kind::Query { .. } => quote!(read),
            Kind::Execute { .. } | Kind::Transaction => quote!(write),
        };
        quote! {
            #(#docs)*
            #vis async fn #name(&self, #(#parameters),*)
                -> ::core::result::Result<#value, crate::store::DbError>
            {
                #(#owned)*
                self.db
                    .#access(move |connection| {
                        <::rusqlite::Connection as #trait_ident>::#name(connection, #(#call),*)
                            .map_err(::core::convert::Into::into)
                    })
                    .await
            }
        }
    }
}

enum Marker {
    Query(LitStr),
    Execute(LitStr),
    Transaction,
}

/// Removes the method's marker attribute and returns what it says.
fn take_marker(attributes: &mut Vec<Attribute>, method: &Ident) -> syn::Result<Marker> {
    let mut found = None;
    let mut error = None;
    attributes.retain(|attribute| {
        let marker = if attribute.path().is_ident("query") {
            attribute.parse_args().map(Marker::Query)
        } else if attribute.path().is_ident("execute") {
            attribute.parse_args().map(Marker::Execute)
        } else if attribute.path().is_ident("transaction") {
            Ok(Marker::Transaction)
        } else {
            return true;
        };
        match (marker, &found) {
            (Ok(marker), None) => found = Some(marker),
            (Ok(_), Some(_)) => {
                error = Some(Error::new(
                    attribute.span(),
                    "a #[dao] method takes exactly one of #[query], #[execute] or #[transaction]",
                ));
            }
            (Err(parse), _) => error = Some(parse),
        }
        false
    });
    if let Some(error) = error {
        return Err(error);
    }
    found.ok_or_else(|| {
        Error::new(
            method.span(),
            "mark each #[dao] method with #[query(\"…\")], #[execute(\"…\")] or #[transaction]",
        )
    })
}

fn reject_body(function: &TraitItemFn, marker: &str) -> syn::Result<()> {
    match &function.default {
        Some(body) => Err(Error::new(
            body.span(),
            format!("a {marker} method has no body; #[dao] writes it from the SQL"),
        )),
        None => Ok(()),
    }
}

/// The method's arguments after `&self`.
fn arguments(function: &TraitItemFn) -> syn::Result<Vec<Argument>> {
    let mut inputs = function.sig.inputs.iter();
    match inputs.next() {
        Some(FnArg::Receiver(receiver))
            if receiver.reference.is_some() && receiver.mutability.is_none() => {}
        _ => {
            return Err(Error::new(
                function.sig.span(),
                "a #[dao] method takes `&self` first",
            ));
        }
    }
    inputs
        .map(|input| match input {
            FnArg::Typed(typed) => match typed.pat.as_ref() {
                Pat::Ident(pattern) => Ok(Argument {
                    name: pattern.ident.clone(),
                    ty: (*typed.ty).clone(),
                }),
                other => Err(Error::new(other.span(), "use a plain argument name")),
            },
            FnArg::Receiver(receiver) => Err(Error::new(receiver.span(), "unexpected receiver")),
        })
        .collect()
}

/// `T` from a declared `rusqlite::Result<T>`.
fn rusqlite_result_value(output: &ReturnType) -> syn::Result<Type> {
    let error = |span| Error::new(span, "a #[dao] method returns `rusqlite::Result<…>`");
    let ReturnType::Type(_, ty) = output else {
        return Err(error(output.span()));
    };
    let Type::Path(path) = ty.as_ref() else {
        return Err(error(ty.span()));
    };
    let segments: Vec<_> = path.path.segments.iter().collect();
    let [crate_segment, result] = segments.as_slice() else {
        return Err(error(ty.span()));
    };
    if crate_segment.ident != "rusqlite" || result.ident != "Result" {
        return Err(error(ty.span()));
    }
    single_generic(&result.arguments).ok_or_else(|| error(ty.span()))
}

fn rows(value: &Type) -> Rows {
    match container(value) {
        Some(("Vec", row)) => Rows::Many(Box::new(row)),
        Some(("Option", row)) => Rows::Optional(Box::new(row)),
        _ => Rows::One(Box::new(value.clone())),
    }
}

fn outcome(value: &Type) -> syn::Result<Outcome> {
    match value {
        Type::Tuple(tuple) if tuple.elems.is_empty() => Ok(Outcome::Nothing),
        Type::Path(path) if path.path.is_ident("usize") => Ok(Outcome::Changed),
        Type::Path(path) if path.path.is_ident("i64") => Ok(Outcome::InsertId),
        other => Err(Error::new(
            other.span(),
            "an #[execute] method returns `usize` (rows changed), `i64` (last insert rowid) or `()`",
        )),
    }
}

/// `("Vec", T)` for `Vec<T>`, `("Option", T)` for `Option<T>`.
fn container(ty: &Type) -> Option<(&'static str, Type)> {
    let Type::Path(path) = ty else { return None };
    let last = path.path.segments.last()?;
    let name = ["Vec", "Option"]
        .into_iter()
        .find(|name| last.ident == name)?;
    Some((name, single_generic(&last.arguments)?))
}

fn single_generic(arguments: &PathArguments) -> Option<Type> {
    let PathArguments::AngleBracketed(arguments) = arguments else {
        return None;
    };
    match arguments.args.iter().collect::<Vec<_>>().as_slice() {
        [GenericArgument::Type(ty)] => Some(ty.clone()),
        _ => None,
    }
}

fn is_reference(ty: &Type) -> bool {
    matches!(ty, Type::Reference(_))
}

/// Every `:name` in the SQL must be an argument, and every argument a `:name`.
fn check_parameters(sql: &LitStr, arguments: &[Argument]) -> syn::Result<()> {
    let names =
        named_parameters(&sql.value()).map_err(|message| Error::new(sql.span(), message))?;
    if let Some(unbound) = names.iter().find(|name| {
        !arguments
            .iter()
            .any(|argument| argument.name == name.as_str())
    }) {
        return Err(Error::new(
            sql.span(),
            format!("`:{unbound}` has no argument with that name"),
        ));
    }
    if let Some(unused) = arguments
        .iter()
        .find(|argument| !names.contains(&argument.name.to_string()))
    {
        return Err(Error::new(
            unused.name.span(),
            format!("argument `{}` is not used in the SQL", unused.name),
        ));
    }
    Ok(())
}

/// The `:name` parameters of `sql`, skipping string literals, quoted
/// identifiers and comments.
fn named_parameters(sql: &str) -> Result<BTreeSet<String>, &'static str> {
    let mut names = BTreeSet::new();
    let mut chars = sql.chars().peekable();
    while let Some(c) = chars.next() {
        match c {
            '\'' | '"' | '`' => {
                for inner in chars.by_ref() {
                    if inner == c {
                        break;
                    }
                }
            }
            '[' => {
                for inner in chars.by_ref() {
                    if inner == ']' {
                        break;
                    }
                }
            }
            '-' if chars.peek() == Some(&'-') => {
                for inner in chars.by_ref() {
                    if inner == '\n' {
                        break;
                    }
                }
            }
            '/' if chars.peek() == Some(&'*') => {
                chars.next();
                let mut previous = None;
                for inner in chars.by_ref() {
                    if previous == Some('*') && inner == '/' {
                        break;
                    }
                    previous = Some(inner);
                }
            }
            '?' | '@' | '$' => {
                return Err("use `:name` parameters, bound from the method's arguments");
            }
            ':' => {
                let mut name = String::new();
                while let Some(&next) = chars.peek() {
                    if !(next.is_ascii_alphanumeric() || next == '_') {
                        break;
                    }
                    name.push(next);
                    chars.next();
                }
                if !name.is_empty() {
                    names.insert(name);
                }
            }
            _ => {}
        }
    }
    Ok(names)
}

#[cfg(test)]
mod tests {
    use super::named_parameters;

    fn names(sql: &str) -> Vec<String> {
        named_parameters(sql).unwrap().into_iter().collect()
    }

    #[test]
    fn finds_each_named_parameter_once() {
        assert_eq!(
            names("SELECT * FROM t WHERE a = :a AND b > :b_2 OR a = :a"),
            vec!["a".to_owned(), "b_2".to_owned()]
        );
    }

    #[test]
    fn ignores_colons_inside_literals_identifiers_and_comments() {
        // A `:word` in a string or comment is text, not a parameter; binding
        // it would fail at runtime.
        let sql = "SELECT ':x', \"col:y\", [z:w] FROM t -- :comment\n WHERE a = :a /* :b */";
        assert_eq!(names(sql), vec!["a".to_owned()]);
    }

    #[test]
    fn rejects_positional_parameters() {
        assert!(named_parameters("SELECT * FROM t WHERE a = ?1").is_err());
    }
}
