// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(pvm_runtimeFFI)
import pvm_runtimeFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_pvm_runtime_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_pvm_runtime_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }

    init(rawBufferPointer: UnsafeRawBufferPointer) {
        self.init(
            len: Int32(rawBufferPointer.count),
            data: rawBufferPointer.baseAddress?.assumingMemoryBound(to: UInt8.self)
        )
    }
}

// Converter for `&[u8]` / `[ByRef] bytes` arguments.
//
// Conforms to `FfiConverter` so the compiler enforces the full converter
// method set. Only the scope-bound `lower(_:_body:)` overload is sound —
// zero-copy byte buffers only flow foreign -> Rust, and only in argument
// position. The four protocol-witness methods (`lift`, `lower`, `read`,
// `write`) `fatalError` at runtime if anyone reaches them.
//
// The scope-bound `lower` takes a closure because the `ForeignBytes`
// pointer is only guaranteed valid for the duration of
// `Data.withUnsafeBytes`. Callers must run the full FFI call inside
// the closure body.
fileprivate enum FfiConverterByRefBytes: FfiConverter {
    typealias SwiftType = Data
    typealias FfiType = ForeignBytes

    static func lower<R>(_ value: Data, _ body: (ForeignBytes) throws -> R) rethrows -> R {
        return try value.withUnsafeBytes { rawBuf in
            try body(ForeignBytes(rawBufferPointer: rawBuf))
        }
    }

    static func lower(_ value: Data) -> ForeignBytes {
        fatalError("ByRef bytes cannot use the plain lower: returning ForeignBytes escapes the Data.withUnsafeBytes scope. Use the scope-bound lower(_:_body:) overload instead.")
    }

    static func lift(_ value: ForeignBytes) throws -> Data {
        fatalError("ByRef bytes cannot be lifted: zero-copy &[u8] only flows foreign->Rust")
    }

    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        fatalError("ByRef bytes cannot be read from a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }

    static func write(_ value: Data, into buf: inout [UInt8]) {
        fatalError("ByRef bytes cannot be written to a buffer: zero-copy &[u8] is only supported in argument position, not nested in records/options/etc.")
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsurePvmRuntimeInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
// Initial value and increment amount for handles.
// These ensure that SWIFT handles always have the lowest bit set
fileprivate let UNIFFI_HANDLEMAP_INITIAL: UInt64 = 1
fileprivate let UNIFFI_HANDLEMAP_DELTA: UInt64 = 2

fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = UNIFFI_HANDLEMAP_INITIAL

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            return doInsert(obj)
        }
    }

    // Low-level insert function, this assumes `lock` is held.
    private func doInsert(_ obj: T) -> UInt64 {
        let handle = currentHandle
        currentHandle += UNIFFI_HANDLEMAP_DELTA
        map[handle] = obj
        return handle
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

     func clone(handle: UInt64) throws -> UInt64 {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return doInsert(obj)
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt16: FfiConverterPrimitive {
    typealias FfiType = UInt16
    typealias SwiftType = UInt16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterInt16: FfiConverterPrimitive {
    typealias FfiType = Int16
    typealias SwiftType = Int16

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Int16 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Int16, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        // Use Swift's native UTF-8 decoder; `String(bytes:encoding:.utf8)` goes
        // through Foundation's NSString and silently strips a leading U+FEFF BOM.
        // Invalid UTF-8 substitutes U+FFFD instead of trapping (unreachable
        // given Rust's `String` invariant).
        return String(decoding: bytes, as: UTF8.self)
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        // See `lift` above for why we avoid Foundation's NSString-backed decoder here.
        return String(decoding: try readBytes(&buf, count: Int(len)), as: UTF8.self)
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}




public protocol NativePvmRuntimeProtocol: AnyObject, Sendable {

    func backend() throws  -> String

    func configureNativeGpu(width: UInt32, height: UInt32) throws

    func gpuReady() throws  -> Bool

    func `init`() throws

    func isExited() throws  -> Bool

    func lastGasUsed() throws  -> UInt64

    func renderNativeGpu() throws  -> NativePvmGpuFrame?

    func resizeNativeGpu(width: UInt32, height: UInt32) throws

    func sendGpuEvent(bytes: Data) throws

    func sendInput(eventType: NativePvmInputEventType, code: UInt8, x: UInt16, y: UInt16) throws

    func sendMotionSample(bytes: Data) throws

    func setGpuCapabilities(bytes: Data) throws

    func setMotionAvailability(availability: NativePvmMotionAvailability) throws

    func takeAudio() throws  -> NativePvmAudioChunk?

    func takeFrame() throws  -> NativePvmFrame?

    func takeGpuBatch() throws  -> NativePvmGpuBatch?

    func takeLog() throws  -> String?

    func takeSave() throws  -> Data?

    func takeTri2d() throws  -> NativePvmTri2dFrame?

    func update() throws

    func usesMotion() throws  -> Bool

}
open class NativePvmRuntime: NativePvmRuntimeProtocol, @unchecked Sendable {
    fileprivate let handle: UInt64

    /// Used to instantiate a [FFIObject] without an actual handle, for fakes in tests, mostly.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public struct NoHandle {
        public init() {}
    }

    // TODO: We'd like this to be `private` but for Swifty reasons,
    // we can't implement `FfiConverter` without making this `required` and we can't
    // make it `required` without making it `public`.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    required public init(unsafeFromHandle handle: UInt64) {
        self.handle = handle
    }

    // This constructor can be used to instantiate a fake object.
    // - Parameter noHandle: Placeholder value so we can have a constructor separate from the default empty one that may be implemented for classes extending [FFIObject].
    //
    // - Warning:
    //     Any object instantiated with this constructor cannot be passed to an actual Rust-backed object. Since there isn't a backing handle the FFI lower functions will crash.
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public init(noHandle: NoHandle) {
        self.handle = 0
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public func uniffiCloneHandle() -> UInt64 {
        return try! rustCall { uniffi_pvm_runtime_fn_clone_nativepvmruntime(self.handle, $0) }
    }
public convenience init(program: Data, assets: [NativePvmAsset], presentation: NativePvmPresentationProfile, audioEnabled: Bool, maxGasPerUpdate: UInt64)throws  {
    let handle =
        try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_constructor_nativepvmruntime_new(
        FfiConverterData.lower(program),
        FfiConverterSequenceTypeNativePvmAsset.lower(assets),
        FfiConverterTypeNativePvmPresentationProfile_lower(presentation),
        FfiConverterBool.lower(audioEnabled),
        FfiConverterUInt64.lower(maxGasPerUpdate),uniffiCallStatus
    )
}
    self.init(unsafeFromHandle: handle)
}

    deinit {
        if handle == 0 {
            // Mock objects have handle=0 don't try to free them
            return
        }

        try! rustCall { uniffi_pvm_runtime_fn_free_nativepvmruntime(handle, $0) }
    }




open func backend()throws  -> String  {
    return try  FfiConverterString.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_backend(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func configureNativeGpu(width: UInt32, height: UInt32)throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_configure_native_gpu(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),uniffiCallStatus
    )
}
}

open func gpuReady()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_gpu_ready(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func `init`()throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_init(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}

open func isExited()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_is_exited(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func lastGasUsed()throws  -> UInt64  {
    return try  FfiConverterUInt64.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_last_gas_used(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func renderNativeGpu()throws  -> NativePvmGpuFrame?  {
    return try  FfiConverterOptionTypeNativePvmGpuFrame.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_render_native_gpu(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func resizeNativeGpu(width: UInt32, height: UInt32)throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_resize_native_gpu(
            self.uniffiCloneHandle(),
        FfiConverterUInt32.lower(width),
        FfiConverterUInt32.lower(height),uniffiCallStatus
    )
}
}

open func sendGpuEvent(bytes: Data)throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_send_gpu_event(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(bytes),uniffiCallStatus
    )
}
}

open func sendInput(eventType: NativePvmInputEventType, code: UInt8, x: UInt16, y: UInt16)throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_send_input(
            self.uniffiCloneHandle(),
        FfiConverterTypeNativePvmInputEventType_lower(eventType),
        FfiConverterUInt8.lower(code),
        FfiConverterUInt16.lower(x),
        FfiConverterUInt16.lower(y),uniffiCallStatus
    )
}
}

open func sendMotionSample(bytes: Data)throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_send_motion_sample(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(bytes),uniffiCallStatus
    )
}
}

open func setGpuCapabilities(bytes: Data)throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_set_gpu_capabilities(
            self.uniffiCloneHandle(),
        FfiConverterData.lower(bytes),uniffiCallStatus
    )
}
}

open func setMotionAvailability(availability: NativePvmMotionAvailability)throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_set_motion_availability(
            self.uniffiCloneHandle(),
        FfiConverterTypeNativePvmMotionAvailability_lower(availability),uniffiCallStatus
    )
}
}

open func takeAudio()throws  -> NativePvmAudioChunk?  {
    return try  FfiConverterOptionTypeNativePvmAudioChunk.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_take_audio(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func takeFrame()throws  -> NativePvmFrame?  {
    return try  FfiConverterOptionTypeNativePvmFrame.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_take_frame(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func takeGpuBatch()throws  -> NativePvmGpuBatch?  {
    return try  FfiConverterOptionTypeNativePvmGpuBatch.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_take_gpu_batch(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func takeLog()throws  -> String?  {
    return try  FfiConverterOptionString.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_take_log(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func takeSave()throws  -> Data?  {
    return try  FfiConverterOptionData.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_take_save(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func takeTri2d()throws  -> NativePvmTri2dFrame?  {
    return try  FfiConverterOptionTypeNativePvmTri2dFrame.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_take_tri2d(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}

open func update()throws   {try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_update(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
}
}

open func usesMotion()throws  -> Bool  {
    return try  FfiConverterBool.lift(try rustCallWithError(FfiConverterTypeNativePvmError_lift) {
        uniffiCallStatus in
    uniffi_pvm_runtime_fn_method_nativepvmruntime_uses_motion(
            self.uniffiCloneHandle(),uniffiCallStatus
    )
})
}



}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmRuntime: FfiConverter {
    typealias FfiType = UInt64
    typealias SwiftType = NativePvmRuntime

    public static func lift(_ handle: UInt64) throws -> NativePvmRuntime {
        return NativePvmRuntime(unsafeFromHandle: handle)
    }

    public static func lower(_ value: NativePvmRuntime) -> UInt64 {
        return value.uniffiCloneHandle()
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmRuntime {
        let handle: UInt64 = try readInt(&buf)
        return try lift(handle)
    }

    public static func write(_ value: NativePvmRuntime, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmRuntime_lift(_ handle: UInt64) throws -> NativePvmRuntime {
    return try FfiConverterTypeNativePvmRuntime.lift(handle)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmRuntime_lower(_ value: NativePvmRuntime) -> UInt64 {
    return FfiConverterTypeNativePvmRuntime.lower(value)
}




public struct NativePvmAsset: Equatable, Hashable {
    public var path: String
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(path: String, bytes: Data) {
        self.path = path
        self.bytes = bytes
    }




}

#if compiler(>=6)
extension NativePvmAsset: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmAsset: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmAsset {
        return
            try NativePvmAsset(
                path: FfiConverterString.read(from: &buf),
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: NativePvmAsset, into buf: inout [UInt8]) {
        FfiConverterString.write(value.path, into: &buf)
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmAsset_lift(_ buf: RustBuffer) throws -> NativePvmAsset {
    return try FfiConverterTypeNativePvmAsset.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmAsset_lower(_ value: NativePvmAsset) -> RustBuffer {
    return FfiConverterTypeNativePvmAsset.lower(value)
}


public struct NativePvmAudioChunk: Equatable, Hashable {
    public var samples: [Int16]
    public var sampleRate: UInt32
    public var channels: UInt32

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(samples: [Int16], sampleRate: UInt32, channels: UInt32) {
        self.samples = samples
        self.sampleRate = sampleRate
        self.channels = channels
    }




}

#if compiler(>=6)
extension NativePvmAudioChunk: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmAudioChunk: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmAudioChunk {
        return
            try NativePvmAudioChunk(
                samples: FfiConverterSequenceInt16.read(from: &buf),
                sampleRate: FfiConverterUInt32.read(from: &buf),
                channels: FfiConverterUInt32.read(from: &buf)
        )
    }

    public static func write(_ value: NativePvmAudioChunk, into buf: inout [UInt8]) {
        FfiConverterSequenceInt16.write(value.samples, into: &buf)
        FfiConverterUInt32.write(value.sampleRate, into: &buf)
        FfiConverterUInt32.write(value.channels, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmAudioChunk_lift(_ buf: RustBuffer) throws -> NativePvmAudioChunk {
    return try FfiConverterTypeNativePvmAudioChunk.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmAudioChunk_lower(_ value: NativePvmAudioChunk) -> RustBuffer {
    return FfiConverterTypeNativePvmAudioChunk.lower(value)
}


public struct NativePvmFrame: Equatable, Hashable {
    public var width: UInt32
    public var height: UInt32
    public var argb: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: UInt32, height: UInt32, argb: Data) {
        self.width = width
        self.height = height
        self.argb = argb
    }




}

#if compiler(>=6)
extension NativePvmFrame: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmFrame: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmFrame {
        return
            try NativePvmFrame(
                width: FfiConverterUInt32.read(from: &buf),
                height: FfiConverterUInt32.read(from: &buf),
                argb: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: NativePvmFrame, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterData.write(value.argb, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmFrame_lift(_ buf: RustBuffer) throws -> NativePvmFrame {
    return try FfiConverterTypeNativePvmFrame.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmFrame_lower(_ value: NativePvmFrame) -> RustBuffer {
    return FfiConverterTypeNativePvmFrame.lower(value)
}


public struct NativePvmGpuBatch: Equatable, Hashable {
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(bytes: Data) {
        self.bytes = bytes
    }




}

#if compiler(>=6)
extension NativePvmGpuBatch: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmGpuBatch: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmGpuBatch {
        return
            try NativePvmGpuBatch(
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: NativePvmGpuBatch, into buf: inout [UInt8]) {
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmGpuBatch_lift(_ buf: RustBuffer) throws -> NativePvmGpuBatch {
    return try FfiConverterTypeNativePvmGpuBatch.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmGpuBatch_lower(_ value: NativePvmGpuBatch) -> RustBuffer {
    return FfiConverterTypeNativePvmGpuBatch.lower(value)
}


public struct NativePvmGpuFrame: Equatable, Hashable {
    public var width: UInt32
    public var height: UInt32
    public var rgba: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: UInt32, height: UInt32, rgba: Data) {
        self.width = width
        self.height = height
        self.rgba = rgba
    }




}

#if compiler(>=6)
extension NativePvmGpuFrame: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmGpuFrame: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmGpuFrame {
        return
            try NativePvmGpuFrame(
                width: FfiConverterUInt32.read(from: &buf),
                height: FfiConverterUInt32.read(from: &buf),
                rgba: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: NativePvmGpuFrame, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterData.write(value.rgba, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmGpuFrame_lift(_ buf: RustBuffer) throws -> NativePvmGpuFrame {
    return try FfiConverterTypeNativePvmGpuFrame.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmGpuFrame_lower(_ value: NativePvmGpuFrame) -> RustBuffer {
    return FfiConverterTypeNativePvmGpuFrame.lower(value)
}


public struct NativePvmTri2dFrame: Equatable, Hashable {
    public var width: UInt32
    public var height: UInt32
    public var drawCount: UInt32
    public var vertexCount: UInt32
    public var indexCount: UInt32
    public var bytes: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(width: UInt32, height: UInt32, drawCount: UInt32, vertexCount: UInt32, indexCount: UInt32, bytes: Data) {
        self.width = width
        self.height = height
        self.drawCount = drawCount
        self.vertexCount = vertexCount
        self.indexCount = indexCount
        self.bytes = bytes
    }




}

#if compiler(>=6)
extension NativePvmTri2dFrame: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmTri2dFrame: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmTri2dFrame {
        return
            try NativePvmTri2dFrame(
                width: FfiConverterUInt32.read(from: &buf),
                height: FfiConverterUInt32.read(from: &buf),
                drawCount: FfiConverterUInt32.read(from: &buf),
                vertexCount: FfiConverterUInt32.read(from: &buf),
                indexCount: FfiConverterUInt32.read(from: &buf),
                bytes: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: NativePvmTri2dFrame, into buf: inout [UInt8]) {
        FfiConverterUInt32.write(value.width, into: &buf)
        FfiConverterUInt32.write(value.height, into: &buf)
        FfiConverterUInt32.write(value.drawCount, into: &buf)
        FfiConverterUInt32.write(value.vertexCount, into: &buf)
        FfiConverterUInt32.write(value.indexCount, into: &buf)
        FfiConverterData.write(value.bytes, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmTri2dFrame_lift(_ buf: RustBuffer) throws -> NativePvmTri2dFrame {
    return try FfiConverterTypeNativePvmTri2dFrame.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmTri2dFrame_lower(_ value: NativePvmTri2dFrame) -> RustBuffer {
    return FfiConverterTypeNativePvmTri2dFrame.lower(value)
}


public
enum NativePvmError: Swift.Error, Equatable, Hashable, Foundation.LocalizedError {



    case Runtime(detail: String
    )
    case DuplicateAsset(path: String
    )
    case RuntimePoisoned






    public var errorDescription: String? {
        String(reflecting: self)
    }

}

#if compiler(>=6)
extension NativePvmError: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmError: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmError

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmError {
        let variant: Int32 = try readInt(&buf)
        switch variant {




        case 1: return .Runtime(
            detail: try FfiConverterString.read(from: &buf)
            )
        case 2: return .DuplicateAsset(
            path: try FfiConverterString.read(from: &buf)
            )
        case 3: return .RuntimePoisoned

         default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativePvmError, into buf: inout [UInt8]) {
        switch value {





        case let .Runtime(detail):
            writeInt(&buf, Int32(1))
            FfiConverterString.write(detail, into: &buf)


        case let .DuplicateAsset(path):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(path, into: &buf)


        case .RuntimePoisoned:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmError_lift(_ buf: RustBuffer) throws -> NativePvmError {
    return try FfiConverterTypeNativePvmError.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmError_lower(_ value: NativePvmError) -> RustBuffer {
    return FfiConverterTypeNativePvmError.lower(value)
}



public enum NativePvmInputEventType: Equatable, Hashable {

    case keyDown
    case keyUp
    case buttonDown
    case buttonUp
    case pointerMove
    case pointerDelta
    case surfaceMetrics





}

#if compiler(>=6)
extension NativePvmInputEventType: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmInputEventType: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmInputEventType

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmInputEventType {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .keyDown

        case 2: return .keyUp

        case 3: return .buttonDown

        case 4: return .buttonUp

        case 5: return .pointerMove

        case 6: return .pointerDelta

        case 7: return .surfaceMetrics

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativePvmInputEventType, into buf: inout [UInt8]) {
        switch value {


        case .keyDown:
            writeInt(&buf, Int32(1))


        case .keyUp:
            writeInt(&buf, Int32(2))


        case .buttonDown:
            writeInt(&buf, Int32(3))


        case .buttonUp:
            writeInt(&buf, Int32(4))


        case .pointerMove:
            writeInt(&buf, Int32(5))


        case .pointerDelta:
            writeInt(&buf, Int32(6))


        case .surfaceMetrics:
            writeInt(&buf, Int32(7))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmInputEventType_lift(_ buf: RustBuffer) throws -> NativePvmInputEventType {
    return try FfiConverterTypeNativePvmInputEventType.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmInputEventType_lower(_ value: NativePvmInputEventType) -> RustBuffer {
    return FfiConverterTypeNativePvmInputEventType.lower(value)
}




public enum NativePvmMotionAvailability: Equatable, Hashable {

    case unavailable
    case available
    case permissionDenied





}

#if compiler(>=6)
extension NativePvmMotionAvailability: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmMotionAvailability: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmMotionAvailability

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmMotionAvailability {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .unavailable

        case 2: return .available

        case 3: return .permissionDenied

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativePvmMotionAvailability, into buf: inout [UInt8]) {
        switch value {


        case .unavailable:
            writeInt(&buf, Int32(1))


        case .available:
            writeInt(&buf, Int32(2))


        case .permissionDenied:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmMotionAvailability_lift(_ buf: RustBuffer) throws -> NativePvmMotionAvailability {
    return try FfiConverterTypeNativePvmMotionAvailability.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmMotionAvailability_lower(_ value: NativePvmMotionAvailability) -> RustBuffer {
    return FfiConverterTypeNativePvmMotionAvailability.lower(value)
}




public enum NativePvmPresentationProfile: Equatable, Hashable {

    case framebuffer
    case tri2d
    case webGpuRaster





}

#if compiler(>=6)
extension NativePvmPresentationProfile: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeNativePvmPresentationProfile: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmPresentationProfile

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> NativePvmPresentationProfile {
        let variant: Int32 = try readInt(&buf)
        switch variant {

        case 1: return .framebuffer

        case 2: return .tri2d

        case 3: return .webGpuRaster

        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: NativePvmPresentationProfile, into buf: inout [UInt8]) {
        switch value {


        case .framebuffer:
            writeInt(&buf, Int32(1))


        case .tri2d:
            writeInt(&buf, Int32(2))


        case .webGpuRaster:
            writeInt(&buf, Int32(3))

        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmPresentationProfile_lift(_ buf: RustBuffer) throws -> NativePvmPresentationProfile {
    return try FfiConverterTypeNativePvmPresentationProfile.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeNativePvmPresentationProfile_lower(_ value: NativePvmPresentationProfile) -> RustBuffer {
    return FfiConverterTypeNativePvmPresentationProfile.lower(value)
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNativePvmAudioChunk: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmAudioChunk?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNativePvmAudioChunk.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNativePvmAudioChunk.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNativePvmFrame: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmFrame?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNativePvmFrame.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNativePvmFrame.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNativePvmGpuBatch: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmGpuBatch?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNativePvmGpuBatch.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNativePvmGpuBatch.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNativePvmGpuFrame: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmGpuFrame?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNativePvmGpuFrame.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNativePvmGpuFrame.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionTypeNativePvmTri2dFrame: FfiConverterRustBuffer {
    typealias SwiftType = NativePvmTri2dFrame?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterTypeNativePvmTri2dFrame.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterTypeNativePvmTri2dFrame.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceInt16: FfiConverterRustBuffer {
    typealias SwiftType = [Int16]

    public static func write(_ value: [Int16], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterInt16.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [Int16] {
        let len: Int32 = try readInt(&buf)
        var seq = [Int16]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterInt16.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeNativePvmAsset: FfiConverterRustBuffer {
    typealias SwiftType = [NativePvmAsset]

    public static func write(_ value: [NativePvmAsset], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeNativePvmAsset.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [NativePvmAsset] {
        let len: Int32 = try readInt(&buf)
        var seq = [NativePvmAsset]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeNativePvmAsset.read(from: &buf))
        }
        return seq
    }
}

private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 30
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_pvm_runtime_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_backend() != 56657) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_configure_native_gpu() != 23998) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_gpu_ready() != 61888) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_init() != 58620) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_is_exited() != 14672) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_last_gas_used() != 63988) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_render_native_gpu() != 27664) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_resize_native_gpu() != 45190) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_send_gpu_event() != 11805) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_send_input() != 59274) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_send_motion_sample() != 20569) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_set_gpu_capabilities() != 28903) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_set_motion_availability() != 51760) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_take_audio() != 21780) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_take_frame() != 8124) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_take_gpu_batch() != 14686) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_take_log() != 61835) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_take_save() != 52485) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_take_tri2d() != 20193) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_update() != 28698) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_method_nativepvmruntime_uses_motion() != 54507) {
        return InitializationResult.apiChecksumMismatch
    }
    if (uniffi_pvm_runtime_checksum_constructor_nativepvmruntime_new() != 25625) {
        return InitializationResult.apiChecksumMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsurePvmRuntimeInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all