// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

// swiftlint:disable all
import Foundation

// Depending on the consumer's build setup, the low-level FFI code
// might be in a separate module, or it might be compiled inline into
// this module. This is a bit of light hackery to work with both.
#if canImport(truapiFFI)
import truapiFFI
#endif

fileprivate extension RustBuffer {
    // Allocate a new buffer, copying the contents of a `UInt8` array.
    init(bytes: [UInt8]) {
        let rbuf = bytes.withUnsafeBufferPointer { ptr in
            RustBuffer.from(ptr)
        }
        self.init(capacity: rbuf.capacity, len: rbuf.len, data: rbuf.data)
    }

    static func empty() -> RustBuffer {
        RustBuffer(capacity: 0, len:0, data: nil)
    }

    static func from(_ ptr: UnsafeBufferPointer<UInt8>) -> RustBuffer {
        try! rustCall { ffi_truapi_rustbuffer_from_bytes(ForeignBytes(bufferPointer: ptr), $0) }
    }

    // Frees the buffer in place.
    // The buffer must not be used after this is called.
    func deallocate() {
        try! rustCall { ffi_truapi_rustbuffer_free(self, $0) }
    }
}

fileprivate extension ForeignBytes {
    init(bufferPointer: UnsafeBufferPointer<UInt8>) {
        self.init(len: Int32(bufferPointer.count), data: bufferPointer.baseAddress)
    }
}

// For every type used in the interface, we provide helper methods for conveniently
// lifting and lowering that type from C-compatible data, and for reading and writing
// values of that type in a buffer.

// Helper classes/extensions that don't change.
// Someday, this will be in a library of its own.

fileprivate extension Data {
    init(rustBuffer: RustBuffer) {
        self.init(
            bytesNoCopy: rustBuffer.data!,
            count: Int(rustBuffer.len),
            deallocator: .none
        )
    }
}

// Define reader functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.
//
// With external types, one swift source file needs to be able to call the read
// method on another source file's FfiConverter, but then what visibility
// should Reader have?
// - If Reader is fileprivate, then this means the read() must also
//   be fileprivate, which doesn't work with external types.
// - If Reader is internal/public, we'll get compile errors since both source
//   files will try define the same type.
//
// Instead, the read() method and these helper functions input a tuple of data

fileprivate func createReader(data: Data) -> (data: Data, offset: Data.Index) {
    (data: data, offset: 0)
}

// Reads an integer at the current offset, in big-endian order, and advances
// the offset on success. Throws if reading the integer would move the
// offset past the end of the buffer.
fileprivate func readInt<T: FixedWidthInteger>(_ reader: inout (data: Data, offset: Data.Index)) throws -> T {
    let range = reader.offset..<reader.offset + MemoryLayout<T>.size
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    if T.self == UInt8.self {
        let value = reader.data[reader.offset]
        reader.offset += 1
        return value as! T
    }
    var value: T = 0
    let _ = withUnsafeMutableBytes(of: &value, { reader.data.copyBytes(to: $0, from: range)})
    reader.offset = range.upperBound
    return value.bigEndian
}

// Reads an arbitrary number of bytes, to be used to read
// raw bytes, this is useful when lifting strings
fileprivate func readBytes(_ reader: inout (data: Data, offset: Data.Index), count: Int) throws -> Array<UInt8> {
    let range = reader.offset..<(reader.offset+count)
    guard reader.data.count >= range.upperBound else {
        throw UniffiInternalError.bufferOverflow
    }
    var value = [UInt8](repeating: 0, count: count)
    value.withUnsafeMutableBufferPointer({ buffer in
        reader.data.copyBytes(to: buffer, from: range)
    })
    reader.offset = range.upperBound
    return value
}

// Reads a float at the current offset.
fileprivate func readFloat(_ reader: inout (data: Data, offset: Data.Index)) throws -> Float {
    return Float(bitPattern: try readInt(&reader))
}

// Reads a float at the current offset.
fileprivate func readDouble(_ reader: inout (data: Data, offset: Data.Index)) throws -> Double {
    return Double(bitPattern: try readInt(&reader))
}

// Indicates if the offset has reached the end of the buffer.
fileprivate func hasRemaining(_ reader: (data: Data, offset: Data.Index)) -> Bool {
    return reader.offset < reader.data.count
}

// Define writer functionality.  Normally this would be defined in a class or
// struct, but we use standalone functions instead in order to make external
// types work.  See the above discussion on Readers for details.

fileprivate func createWriter() -> [UInt8] {
    return []
}

fileprivate func writeBytes<S>(_ writer: inout [UInt8], _ byteArr: S) where S: Sequence, S.Element == UInt8 {
    writer.append(contentsOf: byteArr)
}

// Writes an integer in big-endian order.
//
// Warning: make sure what you are trying to write
// is in the correct type!
fileprivate func writeInt<T: FixedWidthInteger>(_ writer: inout [UInt8], _ value: T) {
    var value = value.bigEndian
    withUnsafeBytes(of: &value) { writer.append(contentsOf: $0) }
}

fileprivate func writeFloat(_ writer: inout [UInt8], _ value: Float) {
    writeInt(&writer, value.bitPattern)
}

fileprivate func writeDouble(_ writer: inout [UInt8], _ value: Double) {
    writeInt(&writer, value.bitPattern)
}

// Protocol for types that transfer other types across the FFI. This is
// analogous to the Rust trait of the same name.
fileprivate protocol FfiConverter {
    associatedtype FfiType
    associatedtype SwiftType

    static func lift(_ value: FfiType) throws -> SwiftType
    static func lower(_ value: SwiftType) -> FfiType
    static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType
    static func write(_ value: SwiftType, into buf: inout [UInt8])
}

// Types conforming to `Primitive` pass themselves directly over the FFI.
fileprivate protocol FfiConverterPrimitive: FfiConverter where FfiType == SwiftType { }

extension FfiConverterPrimitive {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ value: FfiType) throws -> SwiftType {
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> FfiType {
        return value
    }
}

// Types conforming to `FfiConverterRustBuffer` lift and lower into a `RustBuffer`.
// Used for complex types where it's hard to write a custom lift/lower.
fileprivate protocol FfiConverterRustBuffer: FfiConverter where FfiType == RustBuffer {}

extension FfiConverterRustBuffer {
#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lift(_ buf: RustBuffer) throws -> SwiftType {
        var reader = createReader(data: Data(rustBuffer: buf))
        let value = try read(from: &reader)
        if hasRemaining(reader) {
            throw UniffiInternalError.incompleteData
        }
        buf.deallocate()
        return value
    }

#if swift(>=5.8)
    @_documentation(visibility: private)
#endif
    public static func lower(_ value: SwiftType) -> RustBuffer {
          var writer = createWriter()
          write(value, into: &writer)
          return RustBuffer(bytes: writer)
    }
}
// An error type for FFI errors. These errors occur at the UniFFI level, not
// the library level.
fileprivate enum UniffiInternalError: LocalizedError {
    case bufferOverflow
    case incompleteData
    case unexpectedOptionalTag
    case unexpectedEnumCase
    case unexpectedNullPointer
    case unexpectedRustCallStatusCode
    case unexpectedRustCallError
    case unexpectedStaleHandle
    case rustPanic(_ message: String)

    public var errorDescription: String? {
        switch self {
        case .bufferOverflow: return "Reading the requested value would read past the end of the buffer"
        case .incompleteData: return "The buffer still has data after lifting its containing value"
        case .unexpectedOptionalTag: return "Unexpected optional tag; should be 0 or 1"
        case .unexpectedEnumCase: return "Raw enum value doesn't match any cases"
        case .unexpectedNullPointer: return "Raw pointer value was null"
        case .unexpectedRustCallStatusCode: return "Unexpected RustCallStatus code"
        case .unexpectedRustCallError: return "CALL_ERROR but no errorClass specified"
        case .unexpectedStaleHandle: return "The object in the handle map has been dropped already"
        case let .rustPanic(message): return message
        }
    }
}

fileprivate extension NSLock {
    func withLock<T>(f: () throws -> T) rethrows -> T {
        self.lock()
        defer { self.unlock() }
        return try f()
    }
}

fileprivate let CALL_SUCCESS: Int8 = 0
fileprivate let CALL_ERROR: Int8 = 1
fileprivate let CALL_UNEXPECTED_ERROR: Int8 = 2
fileprivate let CALL_CANCELLED: Int8 = 3

fileprivate extension RustCallStatus {
    init() {
        self.init(
            code: CALL_SUCCESS,
            errorBuf: RustBuffer.init(
                capacity: 0,
                len: 0,
                data: nil
            )
        )
    }
}

private func rustCall<T>(_ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    let neverThrow: ((RustBuffer) throws -> Never)? = nil
    return try makeRustCall(callback, errorHandler: neverThrow)
}

private func rustCallWithError<T, E: Swift.Error>(
    _ errorHandler: @escaping (RustBuffer) throws -> E,
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T) throws -> T {
    try makeRustCall(callback, errorHandler: errorHandler)
}

private func makeRustCall<T, E: Swift.Error>(
    _ callback: (UnsafeMutablePointer<RustCallStatus>) -> T,
    errorHandler: ((RustBuffer) throws -> E)?
) throws -> T {
    uniffiEnsureTruapiInitialized()
    var callStatus = RustCallStatus.init()
    let returnedVal = callback(&callStatus)
    try uniffiCheckCallStatus(callStatus: callStatus, errorHandler: errorHandler)
    return returnedVal
}

private func uniffiCheckCallStatus<E: Swift.Error>(
    callStatus: RustCallStatus,
    errorHandler: ((RustBuffer) throws -> E)?
) throws {
    switch callStatus.code {
        case CALL_SUCCESS:
            return

        case CALL_ERROR:
            if let errorHandler = errorHandler {
                throw try errorHandler(callStatus.errorBuf)
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.unexpectedRustCallError
            }

        case CALL_UNEXPECTED_ERROR:
            // When the rust code sees a panic, it tries to construct a RustBuffer
            // with the message.  But if that code panics, then it just sends back
            // an empty buffer.
            if callStatus.errorBuf.len > 0 {
                throw UniffiInternalError.rustPanic(try FfiConverterString.lift(callStatus.errorBuf))
            } else {
                callStatus.errorBuf.deallocate()
                throw UniffiInternalError.rustPanic("Rust panic")
            }

        case CALL_CANCELLED:
            fatalError("Cancellation not supported yet")

        default:
            throw UniffiInternalError.unexpectedRustCallStatusCode
    }
}

private func uniffiTraitInterfaceCall<T>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> ()
) {
    do {
        try writeReturn(makeCall())
    } catch let error {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}

private func uniffiTraitInterfaceCallWithError<T, E>(
    callStatus: UnsafeMutablePointer<RustCallStatus>,
    makeCall: () throws -> T,
    writeReturn: (T) -> (),
    lowerError: (E) -> RustBuffer
) {
    do {
        try writeReturn(makeCall())
    } catch let error as E {
        callStatus.pointee.code = CALL_ERROR
        callStatus.pointee.errorBuf = lowerError(error)
    } catch {
        callStatus.pointee.code = CALL_UNEXPECTED_ERROR
        callStatus.pointee.errorBuf = FfiConverterString.lower(String(describing: error))
    }
}
fileprivate final class UniffiHandleMap<T>: @unchecked Sendable {
    // All mutation happens with this lock held, which is why we implement @unchecked Sendable.
    private let lock = NSLock()
    private var map: [UInt64: T] = [:]
    private var currentHandle: UInt64 = 1

    func insert(obj: T) -> UInt64 {
        lock.withLock {
            let handle = currentHandle
            currentHandle += 1
            map[handle] = obj
            return handle
        }
    }

     func get(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map[handle] else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    @discardableResult
    func remove(handle: UInt64) throws -> T {
        try lock.withLock {
            guard let obj = map.removeValue(forKey: handle) else {
                throw UniffiInternalError.unexpectedStaleHandle
            }
            return obj
        }
    }

    var count: Int {
        get {
            map.count
        }
    }
}


// Public interface members begin here.


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt8: FfiConverterPrimitive {
    typealias FfiType = UInt8
    typealias SwiftType = UInt8

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt8 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: UInt8, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt32: FfiConverterPrimitive {
    typealias FfiType = UInt32
    typealias SwiftType = UInt32

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt32 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterUInt64: FfiConverterPrimitive {
    typealias FfiType = UInt64
    typealias SwiftType = UInt64

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> UInt64 {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterBool : FfiConverter {
    typealias FfiType = Int8
    typealias SwiftType = Bool

    public static func lift(_ value: Int8) throws -> Bool {
        return value != 0
    }

    public static func lower(_ value: Bool) -> Int8 {
        return value ? 1 : 0
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bool {
        return try lift(readInt(&buf))
    }

    public static func write(_ value: Bool, into buf: inout [UInt8]) {
        writeInt(&buf, lower(value))
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterString: FfiConverter {
    typealias SwiftType = String
    typealias FfiType = RustBuffer

    public static func lift(_ value: RustBuffer) throws -> String {
        defer {
            value.deallocate()
        }
        if value.data == nil {
            return String()
        }
        let bytes = UnsafeBufferPointer<UInt8>(start: value.data!, count: Int(value.len))
        return String(bytes: bytes, encoding: String.Encoding.utf8)!
    }

    public static func lower(_ value: String) -> RustBuffer {
        return value.utf8CString.withUnsafeBufferPointer { ptr in
            // The swift string gives us int8_t, we want uint8_t.
            ptr.withMemoryRebound(to: UInt8.self) { ptr in
                // The swift string gives us a trailing null byte, we don't want it.
                let buf = UnsafeBufferPointer(rebasing: ptr.prefix(upTo: ptr.count - 1))
                return RustBuffer.from(buf)
            }
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> String {
        let len: Int32 = try readInt(&buf)
        return String(bytes: try readBytes(&buf, count: Int(len)), encoding: String.Encoding.utf8)!
    }

    public static func write(_ value: String, into buf: inout [UInt8]) {
        let len = Int32(value.utf8.count)
        writeInt(&buf, len)
        writeBytes(&buf, value.utf8)
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterData: FfiConverterRustBuffer {
    typealias SwiftType = Data

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Data {
        let len: Int32 = try readInt(&buf)
        return Data(try readBytes(&buf, count: Int(len)))
    }

    public static func write(_ value: Data, into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        writeBytes(&buf, value)
    }
}


/**
 * Request to produce an sr25519 VRF signature from a product account over a
 * caller-supplied Merlin transcript.
 */
public struct HostAccountSignVrfRequest {
    /**
     * Account whose key signs the VRF.
     */
    public var account: ProductAccountId
    /**
     * Root domain-separation label: `Transcript::new(transcript_label)`.
     */
    public var transcriptLabel: Data
    /**
     * Transcript items replayed in order as `append_message(label, value)`.
     */
    public var items: [VrfTranscriptItem]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Account whose key signs the VRF.
         */account: ProductAccountId, 
        /**
         * Root domain-separation label: `Transcript::new(transcript_label)`.
         */transcriptLabel: Data, 
        /**
         * Transcript items replayed in order as `append_message(label, value)`.
         */items: [VrfTranscriptItem]) {
        self.account = account
        self.transcriptLabel = transcriptLabel
        self.items = items
    }
}

#if compiler(>=6)
extension HostAccountSignVrfRequest: Sendable {}
#endif


extension HostAccountSignVrfRequest: Equatable, Hashable {
    public static func ==(lhs: HostAccountSignVrfRequest, rhs: HostAccountSignVrfRequest) -> Bool {
        if lhs.account != rhs.account {
            return false
        }
        if lhs.transcriptLabel != rhs.transcriptLabel {
            return false
        }
        if lhs.items != rhs.items {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(account)
        hasher.combine(transcriptLabel)
        hasher.combine(items)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostAccountSignVrfRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostAccountSignVrfRequest {
        return
            try HostAccountSignVrfRequest(
                account: FfiConverterTypeProductAccountId.read(from: &buf), 
                transcriptLabel: FfiConverterData.read(from: &buf), 
                items: FfiConverterSequenceTypeVrfTranscriptItem.read(from: &buf)
        )
    }

    public static func write(_ value: HostAccountSignVrfRequest, into buf: inout [UInt8]) {
        FfiConverterTypeProductAccountId.write(value.account, into: &buf)
        FfiConverterData.write(value.transcriptLabel, into: &buf)
        FfiConverterSequenceTypeVrfTranscriptItem.write(value.items, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostAccountSignVrfRequest_lift(_ buf: RustBuffer) throws -> HostAccountSignVrfRequest {
    return try FfiConverterTypeHostAccountSignVrfRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostAccountSignVrfRequest_lower(_ value: HostAccountSignVrfRequest) -> RustBuffer {
    return FfiConverterTypeHostAccountSignVrfRequest.lower(value)
}


/**
 * Push notification payload.
 *
 * When `scheduled_at` is `Some`, the notification is deferred to the given
 * wall-clock instant (Unix milliseconds UTC). `None` fires immediately,
 * preserving prior behaviour. See [RFC 0019].
 *
 * [RFC 0019]: https://github.com/paritytech/truapi/blob/main/docs/rfcs/0019-scheduled-notifications.md
 */
public struct HostPushNotificationRequest {
    /**
     * Notification text.
     */
    public var text: String
    /**
     * Optional URL to open on tap.
     */
    public var deeplink: String?
    /**
     * Optional Unix timestamp in milliseconds (UTC) at which the notification
     * should fire. `None` fires immediately.
     */
    public var scheduledAt: UInt64?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Notification text.
         */text: String, 
        /**
         * Optional URL to open on tap.
         */deeplink: String?, 
        /**
         * Optional Unix timestamp in milliseconds (UTC) at which the notification
         * should fire. `None` fires immediately.
         */scheduledAt: UInt64?) {
        self.text = text
        self.deeplink = deeplink
        self.scheduledAt = scheduledAt
    }
}

#if compiler(>=6)
extension HostPushNotificationRequest: Sendable {}
#endif


extension HostPushNotificationRequest: Equatable, Hashable {
    public static func ==(lhs: HostPushNotificationRequest, rhs: HostPushNotificationRequest) -> Bool {
        if lhs.text != rhs.text {
            return false
        }
        if lhs.deeplink != rhs.deeplink {
            return false
        }
        if lhs.scheduledAt != rhs.scheduledAt {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(text)
        hasher.combine(deeplink)
        hasher.combine(scheduledAt)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostPushNotificationRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostPushNotificationRequest {
        return
            try HostPushNotificationRequest(
                text: FfiConverterString.read(from: &buf), 
                deeplink: FfiConverterOptionString.read(from: &buf), 
                scheduledAt: FfiConverterOptionUInt64.read(from: &buf)
        )
    }

    public static func write(_ value: HostPushNotificationRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.text, into: &buf)
        FfiConverterOptionString.write(value.deeplink, into: &buf)
        FfiConverterOptionUInt64.write(value.scheduledAt, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostPushNotificationRequest_lift(_ buf: RustBuffer) throws -> HostPushNotificationRequest {
    return try FfiConverterTypeHostPushNotificationRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostPushNotificationRequest_lower(_ value: HostPushNotificationRequest) -> RustBuffer {
    return FfiConverterTypeHostPushNotificationRequest.lower(value)
}


/**
 * Full Substrate extrinsic signing payload with all fields needed for signature
 * generation.
 */
public struct HostSignPayloadData {
    /**
     * Reference block hash.
     */
    public var blockHash: Data
    /**
     * Reference block number.
     */
    public var blockNumber: Data
    /**
     * Mortality era encoding.
     */
    public var era: Data
    /**
     * Chain genesis hash.
     */
    public var genesisHash: Data
    /**
     * SCALE-encoded call data.
     */
    public var method: Data
    /**
     * Account nonce.
     */
    public var nonce: Data
    /**
     * Runtime spec version.
     */
    public var specVersion: Data
    /**
     * Transaction tip.
     */
    public var tip: Data
    /**
     * Transaction format version.
     */
    public var transactionVersion: Data
    /**
     * Extension identifiers.
     */
    public var signedExtensions: [String]
    /**
     * Extrinsic version.
     */
    public var version: UInt32
    /**
     * For multi-asset tips.
     */
    public var assetId: Data?
    /**
     * CheckMetadataHash extension.
     */
    public var metadataHash: Data?
    /**
     * Metadata mode.
     */
    public var mode: UInt32?
    /**
     * Request signed transaction back.
     */
    public var withSignedTransaction: Bool?

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Reference block hash.
         */blockHash: Data, 
        /**
         * Reference block number.
         */blockNumber: Data, 
        /**
         * Mortality era encoding.
         */era: Data, 
        /**
         * Chain genesis hash.
         */genesisHash: Data, 
        /**
         * SCALE-encoded call data.
         */method: Data, 
        /**
         * Account nonce.
         */nonce: Data, 
        /**
         * Runtime spec version.
         */specVersion: Data, 
        /**
         * Transaction tip.
         */tip: Data, 
        /**
         * Transaction format version.
         */transactionVersion: Data, 
        /**
         * Extension identifiers.
         */signedExtensions: [String], 
        /**
         * Extrinsic version.
         */version: UInt32, 
        /**
         * For multi-asset tips.
         */assetId: Data?, 
        /**
         * CheckMetadataHash extension.
         */metadataHash: Data?, 
        /**
         * Metadata mode.
         */mode: UInt32?, 
        /**
         * Request signed transaction back.
         */withSignedTransaction: Bool?) {
        self.blockHash = blockHash
        self.blockNumber = blockNumber
        self.era = era
        self.genesisHash = genesisHash
        self.method = method
        self.nonce = nonce
        self.specVersion = specVersion
        self.tip = tip
        self.transactionVersion = transactionVersion
        self.signedExtensions = signedExtensions
        self.version = version
        self.assetId = assetId
        self.metadataHash = metadataHash
        self.mode = mode
        self.withSignedTransaction = withSignedTransaction
    }
}

#if compiler(>=6)
extension HostSignPayloadData: Sendable {}
#endif


extension HostSignPayloadData: Equatable, Hashable {
    public static func ==(lhs: HostSignPayloadData, rhs: HostSignPayloadData) -> Bool {
        if lhs.blockHash != rhs.blockHash {
            return false
        }
        if lhs.blockNumber != rhs.blockNumber {
            return false
        }
        if lhs.era != rhs.era {
            return false
        }
        if lhs.genesisHash != rhs.genesisHash {
            return false
        }
        if lhs.method != rhs.method {
            return false
        }
        if lhs.nonce != rhs.nonce {
            return false
        }
        if lhs.specVersion != rhs.specVersion {
            return false
        }
        if lhs.tip != rhs.tip {
            return false
        }
        if lhs.transactionVersion != rhs.transactionVersion {
            return false
        }
        if lhs.signedExtensions != rhs.signedExtensions {
            return false
        }
        if lhs.version != rhs.version {
            return false
        }
        if lhs.assetId != rhs.assetId {
            return false
        }
        if lhs.metadataHash != rhs.metadataHash {
            return false
        }
        if lhs.mode != rhs.mode {
            return false
        }
        if lhs.withSignedTransaction != rhs.withSignedTransaction {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(blockHash)
        hasher.combine(blockNumber)
        hasher.combine(era)
        hasher.combine(genesisHash)
        hasher.combine(method)
        hasher.combine(nonce)
        hasher.combine(specVersion)
        hasher.combine(tip)
        hasher.combine(transactionVersion)
        hasher.combine(signedExtensions)
        hasher.combine(version)
        hasher.combine(assetId)
        hasher.combine(metadataHash)
        hasher.combine(mode)
        hasher.combine(withSignedTransaction)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostSignPayloadData: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostSignPayloadData {
        return
            try HostSignPayloadData(
                blockHash: FfiConverterData.read(from: &buf), 
                blockNumber: FfiConverterData.read(from: &buf), 
                era: FfiConverterData.read(from: &buf), 
                genesisHash: FfiConverterData.read(from: &buf), 
                method: FfiConverterData.read(from: &buf), 
                nonce: FfiConverterData.read(from: &buf), 
                specVersion: FfiConverterData.read(from: &buf), 
                tip: FfiConverterData.read(from: &buf), 
                transactionVersion: FfiConverterData.read(from: &buf), 
                signedExtensions: FfiConverterSequenceString.read(from: &buf), 
                version: FfiConverterUInt32.read(from: &buf), 
                assetId: FfiConverterOptionData.read(from: &buf), 
                metadataHash: FfiConverterOptionData.read(from: &buf), 
                mode: FfiConverterOptionUInt32.read(from: &buf), 
                withSignedTransaction: FfiConverterOptionBool.read(from: &buf)
        )
    }

    public static func write(_ value: HostSignPayloadData, into buf: inout [UInt8]) {
        FfiConverterData.write(value.blockHash, into: &buf)
        FfiConverterData.write(value.blockNumber, into: &buf)
        FfiConverterData.write(value.era, into: &buf)
        FfiConverterData.write(value.genesisHash, into: &buf)
        FfiConverterData.write(value.method, into: &buf)
        FfiConverterData.write(value.nonce, into: &buf)
        FfiConverterData.write(value.specVersion, into: &buf)
        FfiConverterData.write(value.tip, into: &buf)
        FfiConverterData.write(value.transactionVersion, into: &buf)
        FfiConverterSequenceString.write(value.signedExtensions, into: &buf)
        FfiConverterUInt32.write(value.version, into: &buf)
        FfiConverterOptionData.write(value.assetId, into: &buf)
        FfiConverterOptionData.write(value.metadataHash, into: &buf)
        FfiConverterOptionUInt32.write(value.mode, into: &buf)
        FfiConverterOptionBool.write(value.withSignedTransaction, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignPayloadData_lift(_ buf: RustBuffer) throws -> HostSignPayloadData {
    return try FfiConverterTypeHostSignPayloadData.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignPayloadData_lower(_ value: HostSignPayloadData) -> RustBuffer {
    return FfiConverterTypeHostSignPayloadData.lower(value)
}


/**
 * Request to sign an extrinsic payload with a product account.
 */
public struct HostSignPayloadRequest {
    /**
     * Product account that will sign this payload.
     */
    public var account: ProductAccountId
    /**
     * The extrinsic payload to sign.
     */
    public var payload: HostSignPayloadData

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product account that will sign this payload.
         */account: ProductAccountId, 
        /**
         * The extrinsic payload to sign.
         */payload: HostSignPayloadData) {
        self.account = account
        self.payload = payload
    }
}

#if compiler(>=6)
extension HostSignPayloadRequest: Sendable {}
#endif


extension HostSignPayloadRequest: Equatable, Hashable {
    public static func ==(lhs: HostSignPayloadRequest, rhs: HostSignPayloadRequest) -> Bool {
        if lhs.account != rhs.account {
            return false
        }
        if lhs.payload != rhs.payload {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(account)
        hasher.combine(payload)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostSignPayloadRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostSignPayloadRequest {
        return
            try HostSignPayloadRequest(
                account: FfiConverterTypeProductAccountId.read(from: &buf), 
                payload: FfiConverterTypeHostSignPayloadData.read(from: &buf)
        )
    }

    public static func write(_ value: HostSignPayloadRequest, into buf: inout [UInt8]) {
        FfiConverterTypeProductAccountId.write(value.account, into: &buf)
        FfiConverterTypeHostSignPayloadData.write(value.payload, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignPayloadRequest_lift(_ buf: RustBuffer) throws -> HostSignPayloadRequest {
    return try FfiConverterTypeHostSignPayloadRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignPayloadRequest_lower(_ value: HostSignPayloadRequest) -> RustBuffer {
    return FfiConverterTypeHostSignPayloadRequest.lower(value)
}


/**
 * Sign a Substrate extrinsic payload with a non-product (legacy) account.
 * Contains the same fields as [`HostSignPayloadRequest`] minus `address`
 * (replaced by `signer`).
 */
public struct HostSignPayloadWithLegacyAccountRequest {
    /**
     * Signer address (SS58 or hex) of the legacy account.
     */
    public var signer: String
    /**
     * The extrinsic payload to sign.
     */
    public var payload: HostSignPayloadData

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Signer address (SS58 or hex) of the legacy account.
         */signer: String, 
        /**
         * The extrinsic payload to sign.
         */payload: HostSignPayloadData) {
        self.signer = signer
        self.payload = payload
    }
}

#if compiler(>=6)
extension HostSignPayloadWithLegacyAccountRequest: Sendable {}
#endif


extension HostSignPayloadWithLegacyAccountRequest: Equatable, Hashable {
    public static func ==(lhs: HostSignPayloadWithLegacyAccountRequest, rhs: HostSignPayloadWithLegacyAccountRequest) -> Bool {
        if lhs.signer != rhs.signer {
            return false
        }
        if lhs.payload != rhs.payload {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(signer)
        hasher.combine(payload)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostSignPayloadWithLegacyAccountRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostSignPayloadWithLegacyAccountRequest {
        return
            try HostSignPayloadWithLegacyAccountRequest(
                signer: FfiConverterString.read(from: &buf), 
                payload: FfiConverterTypeHostSignPayloadData.read(from: &buf)
        )
    }

    public static func write(_ value: HostSignPayloadWithLegacyAccountRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.signer, into: &buf)
        FfiConverterTypeHostSignPayloadData.write(value.payload, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignPayloadWithLegacyAccountRequest_lift(_ buf: RustBuffer) throws -> HostSignPayloadWithLegacyAccountRequest {
    return try FfiConverterTypeHostSignPayloadWithLegacyAccountRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignPayloadWithLegacyAccountRequest_lower(_ value: HostSignPayloadWithLegacyAccountRequest) -> RustBuffer {
    return FfiConverterTypeHostSignPayloadWithLegacyAccountRequest.lower(value)
}


/**
 * A raw signing request pairing an account with the payload to sign.
 */
public struct HostSignRawRequest {
    /**
     * Product account that will sign this payload.
     */
    public var account: ProductAccountId
    /**
     * The payload to sign.
     */
    public var payload: RawPayload

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product account that will sign this payload.
         */account: ProductAccountId, 
        /**
         * The payload to sign.
         */payload: RawPayload) {
        self.account = account
        self.payload = payload
    }
}

#if compiler(>=6)
extension HostSignRawRequest: Sendable {}
#endif


extension HostSignRawRequest: Equatable, Hashable {
    public static func ==(lhs: HostSignRawRequest, rhs: HostSignRawRequest) -> Bool {
        if lhs.account != rhs.account {
            return false
        }
        if lhs.payload != rhs.payload {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(account)
        hasher.combine(payload)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostSignRawRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostSignRawRequest {
        return
            try HostSignRawRequest(
                account: FfiConverterTypeProductAccountId.read(from: &buf), 
                payload: FfiConverterTypeRawPayload.read(from: &buf)
        )
    }

    public static func write(_ value: HostSignRawRequest, into buf: inout [UInt8]) {
        FfiConverterTypeProductAccountId.write(value.account, into: &buf)
        FfiConverterTypeRawPayload.write(value.payload, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignRawRequest_lift(_ buf: RustBuffer) throws -> HostSignRawRequest {
    return try FfiConverterTypeHostSignRawRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignRawRequest_lower(_ value: HostSignRawRequest) -> RustBuffer {
    return FfiConverterTypeHostSignRawRequest.lower(value)
}


/**
 * Sign raw bytes with a non-product (legacy) account. The signer field
 * identifies which legacy account to use.
 */
public struct HostSignRawWithLegacyAccountRequest {
    /**
     * Signer address (SS58 or hex) of the legacy account.
     */
    public var signer: String
    /**
     * The data to sign.
     */
    public var payload: RawPayload

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Signer address (SS58 or hex) of the legacy account.
         */signer: String, 
        /**
         * The data to sign.
         */payload: RawPayload) {
        self.signer = signer
        self.payload = payload
    }
}

#if compiler(>=6)
extension HostSignRawWithLegacyAccountRequest: Sendable {}
#endif


extension HostSignRawWithLegacyAccountRequest: Equatable, Hashable {
    public static func ==(lhs: HostSignRawWithLegacyAccountRequest, rhs: HostSignRawWithLegacyAccountRequest) -> Bool {
        if lhs.signer != rhs.signer {
            return false
        }
        if lhs.payload != rhs.payload {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(signer)
        hasher.combine(payload)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostSignRawWithLegacyAccountRequest: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostSignRawWithLegacyAccountRequest {
        return
            try HostSignRawWithLegacyAccountRequest(
                signer: FfiConverterString.read(from: &buf), 
                payload: FfiConverterTypeRawPayload.read(from: &buf)
        )
    }

    public static func write(_ value: HostSignRawWithLegacyAccountRequest, into buf: inout [UInt8]) {
        FfiConverterString.write(value.signer, into: &buf)
        FfiConverterTypeRawPayload.write(value.payload, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignRawWithLegacyAccountRequest_lift(_ buf: RustBuffer) throws -> HostSignRawWithLegacyAccountRequest {
    return try FfiConverterTypeHostSignRawWithLegacyAccountRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostSignRawWithLegacyAccountRequest_lower(_ value: HostSignRawWithLegacyAccountRequest) -> RustBuffer {
    return FfiConverterTypeHostSignRawWithLegacyAccountRequest.lower(value)
}


/**
 * Transaction payload for a legacy (non-product) account.
 *
 * Identical to [`ProductAccountTxPayload`] except the signer is a raw
 * 32-byte [`AccountId`].
 */
public struct LegacyAccountTxPayload {
    /**
     * Raw 32-byte public key of the legacy account.
     */
    public var signer: Bytes32
    /**
     * Chain where the transaction will execute.
     */
    public var genesisHash: Bytes32
    /**
     * SCALE-encoded Call data.
     */
    public var callData: Data
    /**
     * Transaction extensions supplied by the caller.
     */
    public var extensions: [TxPayloadExtension]
    /**
     * 0 for Extrinsic V4, runtime-supported value for V5.
     */
    public var txExtVersion: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Raw 32-byte public key of the legacy account.
         */signer: Bytes32, 
        /**
         * Chain where the transaction will execute.
         */genesisHash: Bytes32, 
        /**
         * SCALE-encoded Call data.
         */callData: Data, 
        /**
         * Transaction extensions supplied by the caller.
         */extensions: [TxPayloadExtension], 
        /**
         * 0 for Extrinsic V4, runtime-supported value for V5.
         */txExtVersion: UInt8) {
        self.signer = signer
        self.genesisHash = genesisHash
        self.callData = callData
        self.extensions = extensions
        self.txExtVersion = txExtVersion
    }
}

#if compiler(>=6)
extension LegacyAccountTxPayload: Sendable {}
#endif


extension LegacyAccountTxPayload: Equatable, Hashable {
    public static func ==(lhs: LegacyAccountTxPayload, rhs: LegacyAccountTxPayload) -> Bool {
        if lhs.signer != rhs.signer {
            return false
        }
        if lhs.genesisHash != rhs.genesisHash {
            return false
        }
        if lhs.callData != rhs.callData {
            return false
        }
        if lhs.extensions != rhs.extensions {
            return false
        }
        if lhs.txExtVersion != rhs.txExtVersion {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(signer)
        hasher.combine(genesisHash)
        hasher.combine(callData)
        hasher.combine(extensions)
        hasher.combine(txExtVersion)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeLegacyAccountTxPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> LegacyAccountTxPayload {
        return
            try LegacyAccountTxPayload(
                signer: FfiConverterTypeBytes32.read(from: &buf), 
                genesisHash: FfiConverterTypeBytes32.read(from: &buf), 
                callData: FfiConverterData.read(from: &buf), 
                extensions: FfiConverterSequenceTypeTxPayloadExtension.read(from: &buf), 
                txExtVersion: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: LegacyAccountTxPayload, into buf: inout [UInt8]) {
        FfiConverterTypeBytes32.write(value.signer, into: &buf)
        FfiConverterTypeBytes32.write(value.genesisHash, into: &buf)
        FfiConverterData.write(value.callData, into: &buf)
        FfiConverterSequenceTypeTxPayloadExtension.write(value.extensions, into: &buf)
        FfiConverterUInt8.write(value.txExtVersion, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLegacyAccountTxPayload_lift(_ buf: RustBuffer) throws -> LegacyAccountTxPayload {
    return try FfiConverterTypeLegacyAccountTxPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeLegacyAccountTxPayload_lower(_ value: LegacyAccountTxPayload) -> RustBuffer {
    return FfiConverterTypeLegacyAccountTxPayload.lower(value)
}


/**
 * Identifies a product-specific account by combining a dotNS domain name with a
 * derivation index.
 */
public struct ProductAccountId {
    /**
     * A dotNS domain name identifier (e.g., `"my-product.dot"`).
     */
    public var dotNsIdentifier: String
    /**
     * Account selector within the product subtree.
     */
    public var derivationIndex: DerivationIndex

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * A dotNS domain name identifier (e.g., `"my-product.dot"`).
         */dotNsIdentifier: String, 
        /**
         * Account selector within the product subtree.
         */derivationIndex: DerivationIndex) {
        self.dotNsIdentifier = dotNsIdentifier
        self.derivationIndex = derivationIndex
    }
}

#if compiler(>=6)
extension ProductAccountId: Sendable {}
#endif


extension ProductAccountId: Equatable, Hashable {
    public static func ==(lhs: ProductAccountId, rhs: ProductAccountId) -> Bool {
        if lhs.dotNsIdentifier != rhs.dotNsIdentifier {
            return false
        }
        if lhs.derivationIndex != rhs.derivationIndex {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(dotNsIdentifier)
        hasher.combine(derivationIndex)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProductAccountId: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProductAccountId {
        return
            try ProductAccountId(
                dotNsIdentifier: FfiConverterString.read(from: &buf), 
                derivationIndex: FfiConverterTypeDerivationIndex.read(from: &buf)
        )
    }

    public static func write(_ value: ProductAccountId, into buf: inout [UInt8]) {
        FfiConverterString.write(value.dotNsIdentifier, into: &buf)
        FfiConverterTypeDerivationIndex.write(value.derivationIndex, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductAccountId_lift(_ buf: RustBuffer) throws -> ProductAccountId {
    return try FfiConverterTypeProductAccountId.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductAccountId_lower(_ value: ProductAccountId) -> RustBuffer {
    return FfiConverterTypeProductAccountId.lower(value)
}


/**
 * Transaction payload for a product account.
 *
 * Contains everything the host needs to construct a signed extrinsic.
 * The signer is a [`ProductAccountId`]; the host resolves the
 * corresponding key pair through its account management layer.
 */
public struct ProductAccountTxPayload {
    /**
     * Product account that will sign the transaction.
     */
    public var signer: ProductAccountId
    /**
     * Chain where the transaction will execute.
     */
    public var genesisHash: Bytes32
    /**
     * SCALE-encoded Call data.
     */
    public var callData: Data
    /**
     * Transaction extensions supplied by the caller.
     */
    public var extensions: [TxPayloadExtension]
    /**
     * 0 for Extrinsic V4, runtime-supported value for V5.
     */
    public var txExtVersion: UInt8

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Product account that will sign the transaction.
         */signer: ProductAccountId, 
        /**
         * Chain where the transaction will execute.
         */genesisHash: Bytes32, 
        /**
         * SCALE-encoded Call data.
         */callData: Data, 
        /**
         * Transaction extensions supplied by the caller.
         */extensions: [TxPayloadExtension], 
        /**
         * 0 for Extrinsic V4, runtime-supported value for V5.
         */txExtVersion: UInt8) {
        self.signer = signer
        self.genesisHash = genesisHash
        self.callData = callData
        self.extensions = extensions
        self.txExtVersion = txExtVersion
    }
}

#if compiler(>=6)
extension ProductAccountTxPayload: Sendable {}
#endif


extension ProductAccountTxPayload: Equatable, Hashable {
    public static func ==(lhs: ProductAccountTxPayload, rhs: ProductAccountTxPayload) -> Bool {
        if lhs.signer != rhs.signer {
            return false
        }
        if lhs.genesisHash != rhs.genesisHash {
            return false
        }
        if lhs.callData != rhs.callData {
            return false
        }
        if lhs.extensions != rhs.extensions {
            return false
        }
        if lhs.txExtVersion != rhs.txExtVersion {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(signer)
        hasher.combine(genesisHash)
        hasher.combine(callData)
        hasher.combine(extensions)
        hasher.combine(txExtVersion)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProductAccountTxPayload: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProductAccountTxPayload {
        return
            try ProductAccountTxPayload(
                signer: FfiConverterTypeProductAccountId.read(from: &buf), 
                genesisHash: FfiConverterTypeBytes32.read(from: &buf), 
                callData: FfiConverterData.read(from: &buf), 
                extensions: FfiConverterSequenceTypeTxPayloadExtension.read(from: &buf), 
                txExtVersion: FfiConverterUInt8.read(from: &buf)
        )
    }

    public static func write(_ value: ProductAccountTxPayload, into buf: inout [UInt8]) {
        FfiConverterTypeProductAccountId.write(value.signer, into: &buf)
        FfiConverterTypeBytes32.write(value.genesisHash, into: &buf)
        FfiConverterData.write(value.callData, into: &buf)
        FfiConverterSequenceTypeTxPayloadExtension.write(value.extensions, into: &buf)
        FfiConverterUInt8.write(value.txExtVersion, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductAccountTxPayload_lift(_ buf: RustBuffer) throws -> ProductAccountTxPayload {
    return try FfiConverterTypeProductAccountTxPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductAccountTxPayload_lower(_ value: ProductAccountTxPayload) -> RustBuffer {
    return FfiConverterTypeProductAccountTxPayload.lower(value)
}


/**
 * A product-scoped proof context: a product and a context within it.
 *
 * Hashed (with a `product/<product_id>/` prefix) into the 32-byte context bound
 * to a ring VRF proof, so contexts cannot collide across products and the same
 * member key under different contexts yields unlinkable aliases.
 */
public struct ProductProofContext {
    /**
     * dotNS product identifier (e.g. `"my-product.dot"`) scoping the context.
     */
    public var productId: String
    /**
     * Selector distinguishing contexts within the product; expands to the
     * same 32-byte derivation index as [`ProductAccountId::derivation_index`].
     */
    public var suffix: DerivationIndex

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * dotNS product identifier (e.g. `"my-product.dot"`) scoping the context.
         */productId: String, 
        /**
         * Selector distinguishing contexts within the product; expands to the
         * same 32-byte derivation index as [`ProductAccountId::derivation_index`].
         */suffix: DerivationIndex) {
        self.productId = productId
        self.suffix = suffix
    }
}

#if compiler(>=6)
extension ProductProofContext: Sendable {}
#endif


extension ProductProofContext: Equatable, Hashable {
    public static func ==(lhs: ProductProofContext, rhs: ProductProofContext) -> Bool {
        if lhs.productId != rhs.productId {
            return false
        }
        if lhs.suffix != rhs.suffix {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(productId)
        hasher.combine(suffix)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeProductProofContext: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ProductProofContext {
        return
            try ProductProofContext(
                productId: FfiConverterString.read(from: &buf), 
                suffix: FfiConverterTypeDerivationIndex.read(from: &buf)
        )
    }

    public static func write(_ value: ProductProofContext, into buf: inout [UInt8]) {
        FfiConverterString.write(value.productId, into: &buf)
        FfiConverterTypeDerivationIndex.write(value.suffix, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductProofContext_lift(_ buf: RustBuffer) throws -> ProductProofContext {
    return try FfiConverterTypeProductProofContext.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeProductProofContext_lower(_ value: ProductProofContext) -> RustBuffer {
    return FfiConverterTypeProductProofContext.lower(value)
}


/**
 * Locates a ring for ring VRF operations using only identifiers that are
 * stable across membership changes.
 */
public struct RingLocation {
    /**
     * Genesis hash of the chain hosting the ring.
     */
    public var chainId: Bytes32
    /**
     * Path addressing the ring within the chain.
     */
    public var junctions: [RingLocationJunction]

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Genesis hash of the chain hosting the ring.
         */chainId: Bytes32, 
        /**
         * Path addressing the ring within the chain.
         */junctions: [RingLocationJunction]) {
        self.chainId = chainId
        self.junctions = junctions
    }
}

#if compiler(>=6)
extension RingLocation: Sendable {}
#endif


extension RingLocation: Equatable, Hashable {
    public static func ==(lhs: RingLocation, rhs: RingLocation) -> Bool {
        if lhs.chainId != rhs.chainId {
            return false
        }
        if lhs.junctions != rhs.junctions {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(chainId)
        hasher.combine(junctions)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRingLocation: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RingLocation {
        return
            try RingLocation(
                chainId: FfiConverterTypeBytes32.read(from: &buf), 
                junctions: FfiConverterSequenceTypeRingLocationJunction.read(from: &buf)
        )
    }

    public static func write(_ value: RingLocation, into buf: inout [UInt8]) {
        FfiConverterTypeBytes32.write(value.chainId, into: &buf)
        FfiConverterSequenceTypeRingLocationJunction.write(value.junctions, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRingLocation_lift(_ buf: RustBuffer) throws -> RingLocation {
    return try FfiConverterTypeRingLocation.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRingLocation_lower(_ value: RingLocation) -> RustBuffer {
    return FfiConverterTypeRingLocation.lower(value)
}


/**
 * A signed extension for a transaction payload.
 */
public struct TxPayloadExtension {
    /**
     * Extension name (e.g., `"CheckSpecVersion"`).
     */
    public var id: String
    /**
     * SCALE-encoded extra data (in extrinsic body).
     */
    public var extra: Data
    /**
     * SCALE-encoded implicit data (signed, not in body).
     */
    public var additionalSigned: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Extension name (e.g., `"CheckSpecVersion"`).
         */id: String, 
        /**
         * SCALE-encoded extra data (in extrinsic body).
         */extra: Data, 
        /**
         * SCALE-encoded implicit data (signed, not in body).
         */additionalSigned: Data) {
        self.id = id
        self.extra = extra
        self.additionalSigned = additionalSigned
    }
}

#if compiler(>=6)
extension TxPayloadExtension: Sendable {}
#endif


extension TxPayloadExtension: Equatable, Hashable {
    public static func ==(lhs: TxPayloadExtension, rhs: TxPayloadExtension) -> Bool {
        if lhs.id != rhs.id {
            return false
        }
        if lhs.extra != rhs.extra {
            return false
        }
        if lhs.additionalSigned != rhs.additionalSigned {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(id)
        hasher.combine(extra)
        hasher.combine(additionalSigned)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeTxPayloadExtension: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> TxPayloadExtension {
        return
            try TxPayloadExtension(
                id: FfiConverterString.read(from: &buf), 
                extra: FfiConverterData.read(from: &buf), 
                additionalSigned: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: TxPayloadExtension, into buf: inout [UInt8]) {
        FfiConverterString.write(value.id, into: &buf)
        FfiConverterData.write(value.extra, into: &buf)
        FfiConverterData.write(value.additionalSigned, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxPayloadExtension_lift(_ buf: RustBuffer) throws -> TxPayloadExtension {
    return try FfiConverterTypeTxPayloadExtension.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeTxPayloadExtension_lower(_ value: TxPayloadExtension) -> RustBuffer {
    return FfiConverterTypeTxPayloadExtension.lower(value)
}


/**
 * One `append_message` call replayed against the signing transcript.
 */
public struct VrfTranscriptItem {
    /**
     * Merlin `append_message` label.
     */
    public var label: Data
    /**
     * Merlin `append_message` value.
     */
    public var value: Data

    // Default memberwise initializers are never public by default, so we
    // declare one manually.
    public init(
        /**
         * Merlin `append_message` label.
         */label: Data, 
        /**
         * Merlin `append_message` value.
         */value: Data) {
        self.label = label
        self.value = value
    }
}

#if compiler(>=6)
extension VrfTranscriptItem: Sendable {}
#endif


extension VrfTranscriptItem: Equatable, Hashable {
    public static func ==(lhs: VrfTranscriptItem, rhs: VrfTranscriptItem) -> Bool {
        if lhs.label != rhs.label {
            return false
        }
        if lhs.value != rhs.value {
            return false
        }
        return true
    }

    public func hash(into hasher: inout Hasher) {
        hasher.combine(label)
        hasher.combine(value)
    }
}



#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeVrfTranscriptItem: FfiConverterRustBuffer {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> VrfTranscriptItem {
        return
            try VrfTranscriptItem(
                label: FfiConverterData.read(from: &buf), 
                value: FfiConverterData.read(from: &buf)
        )
    }

    public static func write(_ value: VrfTranscriptItem, into buf: inout [UInt8]) {
        FfiConverterData.write(value.label, into: &buf)
        FfiConverterData.write(value.value, into: &buf)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVrfTranscriptItem_lift(_ buf: RustBuffer) throws -> VrfTranscriptItem {
    return try FfiConverterTypeVrfTranscriptItem.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeVrfTranscriptItem_lower(_ value: VrfTranscriptItem) -> RustBuffer {
    return FfiConverterTypeVrfTranscriptItem.lower(value)
}

// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A resource the host can pre-allocate on behalf of the product (RFC 0010).
 *
 * For the slot-table allowances (`StatementStoreAllowance`,
 * `BulletinAllowance`, `SmartContractAllowance`), pre-allocation is
 * opportunistic and the host may also fulfil the allowance implicitly on the
 * first submission. `AutoSigning` must be requested explicitly through this
 * call.
 */

public enum AllocatableResource {
    
    /**
     * Statement Store slot allowance for the product's own allowance account.
     */
    case statementStoreAllowance
    /**
     * Bulletin chain slot allowance for the product's own allowance account.
     */
    case bulletinAllowance
    /**
     * Pre-warmed PGAS balance for the product account selected by this
     * derivation index.
     */
    case smartContractAllowance(DerivationIndex
    )
    /**
     * Permission to sign on the product's behalf without per-call user prompts.
     */
    case autoSigning
}


#if compiler(>=6)
extension AllocatableResource: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeAllocatableResource: FfiConverterRustBuffer {
    typealias SwiftType = AllocatableResource

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> AllocatableResource {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .statementStoreAllowance
        
        case 2: return .bulletinAllowance
        
        case 3: return .smartContractAllowance(try FfiConverterTypeDerivationIndex.read(from: &buf)
        )
        
        case 4: return .autoSigning
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: AllocatableResource, into buf: inout [UInt8]) {
        switch value {
        
        
        case .statementStoreAllowance:
            writeInt(&buf, Int32(1))
        
        
        case .bulletinAllowance:
            writeInt(&buf, Int32(2))
        
        
        case let .smartContractAllowance(v1):
            writeInt(&buf, Int32(3))
            FfiConverterTypeDerivationIndex.write(v1, into: &buf)
            
        
        case .autoSigning:
            writeInt(&buf, Int32(4))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAllocatableResource_lift(_ buf: RustBuffer) throws -> AllocatableResource {
    return try FfiConverterTypeAllocatableResource.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeAllocatableResource_lower(_ value: AllocatableResource) -> RustBuffer {
    return FfiConverterTypeAllocatableResource.lower(value)
}


extension AllocatableResource: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Account selector within a product subtree: `Either<u32, [u8; 32]>`.
 *
 * `Left` is the primary form — plain indices keep a product's accounts
 * enumerable. `Right` carries a raw 32-byte derivation index for cases where
 * bytes are genuinely necessary. Hosts expand `Left(n)` to the internal
 * 32-byte index (`u32` little-endian plus the index magic).
 */

public enum DerivationIndex {
    
    /**
     * Plain account index.
     */
    case left(UInt32
    )
    /**
     * Raw 32-byte derivation index.
     */
    case right(Bytes32
    )
}


#if compiler(>=6)
extension DerivationIndex: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeDerivationIndex: FfiConverterRustBuffer {
    typealias SwiftType = DerivationIndex

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> DerivationIndex {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .left(try FfiConverterUInt32.read(from: &buf)
        )
        
        case 2: return .right(try FfiConverterTypeBytes32.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: DerivationIndex, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .left(v1):
            writeInt(&buf, Int32(1))
            FfiConverterUInt32.write(v1, into: &buf)
            
        
        case let .right(v1):
            writeInt(&buf, Int32(2))
            FfiConverterTypeBytes32.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDerivationIndex_lift(_ buf: RustBuffer) throws -> DerivationIndex {
    return try FfiConverterTypeDerivationIndex.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeDerivationIndex_lower(_ value: DerivationIndex) -> RustBuffer {
    return FfiConverterTypeDerivationIndex.lower(value)
}


extension DerivationIndex: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Device-capability permission requested from the host (RFC 0002).
 *
 * The user's decision is persisted indefinitely after the first prompt and
 * survives app restarts, whether the decision was grant or deny; the host
 * does not re-prompt on subsequent requests for the same capability.
 */

public enum HostDevicePermissionRequest {
    
    /**
     * Showing system notifications.
     */
    case notifications
    /**
     * Camera capture access.
     */
    case camera
    /**
     * Microphone capture access.
     */
    case microphone
    /**
     * Bluetooth device access.
     */
    case bluetooth
    /**
     * NFC reader access.
     */
    case nfc
    /**
     * Geolocation access.
     */
    case location
    /**
     * Clipboard access.
     */
    case clipboard
    /**
     * Opening URLs outside the host.
     */
    case openUrl
    /**
     * Biometric authentication.
     */
    case biometrics
}


#if compiler(>=6)
extension HostDevicePermissionRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostDevicePermissionRequest: FfiConverterRustBuffer {
    typealias SwiftType = HostDevicePermissionRequest

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostDevicePermissionRequest {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .notifications
        
        case 2: return .camera
        
        case 3: return .microphone
        
        case 4: return .bluetooth
        
        case 5: return .nfc
        
        case 6: return .location
        
        case 7: return .clipboard
        
        case 8: return .openUrl
        
        case 9: return .biometrics
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HostDevicePermissionRequest, into buf: inout [UInt8]) {
        switch value {
        
        
        case .notifications:
            writeInt(&buf, Int32(1))
        
        
        case .camera:
            writeInt(&buf, Int32(2))
        
        
        case .microphone:
            writeInt(&buf, Int32(3))
        
        
        case .bluetooth:
            writeInt(&buf, Int32(4))
        
        
        case .nfc:
            writeInt(&buf, Int32(5))
        
        
        case .location:
            writeInt(&buf, Int32(6))
        
        
        case .clipboard:
            writeInt(&buf, Int32(7))
        
        
        case .openUrl:
            writeInt(&buf, Int32(8))
        
        
        case .biometrics:
            writeInt(&buf, Int32(9))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostDevicePermissionRequest_lift(_ buf: RustBuffer) throws -> HostDevicePermissionRequest {
    return try FfiConverterTypeHostDevicePermissionRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostDevicePermissionRequest_lower(_ value: HostDevicePermissionRequest) -> RustBuffer {
    return FfiConverterTypeHostDevicePermissionRequest.lower(value)
}


extension HostDevicePermissionRequest: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Request to query whether a feature is supported by the host.
 */

public enum HostFeatureSupportedRequest {
    
    /**
     * Ask whether the host can interact with the chain identified by genesis hash.
     */
    case chain(
        /**
         * Chain genesis hash.
         */genesisHash: Data
    )
}


#if compiler(>=6)
extension HostFeatureSupportedRequest: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeHostFeatureSupportedRequest: FfiConverterRustBuffer {
    typealias SwiftType = HostFeatureSupportedRequest

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> HostFeatureSupportedRequest {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .chain(genesisHash: try FfiConverterData.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: HostFeatureSupportedRequest, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .chain(genesisHash):
            writeInt(&buf, Int32(1))
            FfiConverterData.write(genesisHash, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostFeatureSupportedRequest_lift(_ buf: RustBuffer) throws -> HostFeatureSupportedRequest {
    return try FfiConverterTypeHostFeatureSupportedRequest.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeHostFeatureSupportedRequest_lower(_ value: HostFeatureSupportedRequest) -> RustBuffer {
    return FfiConverterTypeHostFeatureSupportedRequest.lower(value)
}


extension HostFeatureSupportedRequest: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Raw data to sign -- either binary bytes or a string message.
 */

public enum RawPayload {
    
    /**
     * Raw binary data to sign.
     */
    case bytes(
        /**
         * Raw binary payload bytes.
         */bytes: Data
    )
    /**
     * String message to sign.
     */
    case payload(
        /**
         * String payload to sign.
         */payload: String
    )
}


#if compiler(>=6)
extension RawPayload: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRawPayload: FfiConverterRustBuffer {
    typealias SwiftType = RawPayload

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RawPayload {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .bytes(bytes: try FfiConverterData.read(from: &buf)
        )
        
        case 2: return .payload(payload: try FfiConverterString.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RawPayload, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .bytes(bytes):
            writeInt(&buf, Int32(1))
            FfiConverterData.write(bytes, into: &buf)
            
        
        case let .payload(payload):
            writeInt(&buf, Int32(2))
            FfiConverterString.write(payload, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRawPayload_lift(_ buf: RustBuffer) throws -> RawPayload {
    return try FfiConverterTypeRawPayload.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRawPayload_lower(_ value: RawPayload) -> RustBuffer {
    return FfiConverterTypeRawPayload.lower(value)
}


extension RawPayload: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * One remote-operation permission requested by the product (RFC 0002).
 *
 * `ChainSubmit`, `PreimageSubmit`, and `StatementSubmit` are also triggered
 * implicitly by the corresponding business calls when not yet granted.
 */

public enum RemotePermission {
    
    /**
     * Outbound HTTP/WebSocket access to a set of domains.
     */
    case remote(
        /**
         * Domain patterns requested by the product.
         */domains: [String]
    )
    /**
     * WebRTC media access.
     */
    case webRtc
    /**
     * Submitting transactions on behalf of the user via `remote_chain_transaction_broadcast`.
     */
    case chainSubmit
    /**
     * Submitting preimages on behalf of the user via `remote_preimage_submit`.
     */
    case preimageSubmit
    /**
     * Submitting statements on behalf of the user via `remote_statement_store_submit`.
     */
    case statementSubmit
}


#if compiler(>=6)
extension RemotePermission: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRemotePermission: FfiConverterRustBuffer {
    typealias SwiftType = RemotePermission

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RemotePermission {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .remote(domains: try FfiConverterSequenceString.read(from: &buf)
        )
        
        case 2: return .webRtc
        
        case 3: return .chainSubmit
        
        case 4: return .preimageSubmit
        
        case 5: return .statementSubmit
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RemotePermission, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .remote(domains):
            writeInt(&buf, Int32(1))
            FfiConverterSequenceString.write(domains, into: &buf)
            
        
        case .webRtc:
            writeInt(&buf, Int32(2))
        
        
        case .chainSubmit:
            writeInt(&buf, Int32(3))
        
        
        case .preimageSubmit:
            writeInt(&buf, Int32(4))
        
        
        case .statementSubmit:
            writeInt(&buf, Int32(5))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemotePermission_lift(_ buf: RustBuffer) throws -> RemotePermission {
    return try FfiConverterTypeRemotePermission.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRemotePermission_lower(_ value: RemotePermission) -> RustBuffer {
    return FfiConverterTypeRemotePermission.lower(value)
}


extension RemotePermission: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * A single step in a [`RingLocation`] path, addressing a ring within a chain.
 */

public enum RingLocationJunction {
    
    /**
     * Pallet instance hosting the ring collection.
     */
    case palletInstance(UInt8
    )
    /**
     * Ring collection identifier within the pallet.
     */
    case collectionId(Data
    )
}


#if compiler(>=6)
extension RingLocationJunction: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeRingLocationJunction: FfiConverterRustBuffer {
    typealias SwiftType = RingLocationJunction

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> RingLocationJunction {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .palletInstance(try FfiConverterUInt8.read(from: &buf)
        )
        
        case 2: return .collectionId(try FfiConverterData.read(from: &buf)
        )
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: RingLocationJunction, into buf: inout [UInt8]) {
        switch value {
        
        
        case let .palletInstance(v1):
            writeInt(&buf, Int32(1))
            FfiConverterUInt8.write(v1, into: &buf)
            
        
        case let .collectionId(v1):
            writeInt(&buf, Int32(2))
            FfiConverterData.write(v1, into: &buf)
            
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRingLocationJunction_lift(_ buf: RustBuffer) throws -> RingLocationJunction {
    return try FfiConverterTypeRingLocationJunction.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeRingLocationJunction_lower(_ value: RingLocationJunction) -> RustBuffer {
    return FfiConverterTypeRingLocationJunction.lower(value)
}


extension RingLocationJunction: Equatable, Hashable {}






// Note that we don't yet support `indirect` for enums.
// See https://github.com/mozilla/uniffi-rs/issues/396 for further discussion.
/**
 * Light or dark variant.
 */

public enum ThemeVariant {
    
    /**
     * Light appearance.
     */
    case light
    /**
     * Dark appearance.
     */
    case dark
}


#if compiler(>=6)
extension ThemeVariant: Sendable {}
#endif

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeThemeVariant: FfiConverterRustBuffer {
    typealias SwiftType = ThemeVariant

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> ThemeVariant {
        let variant: Int32 = try readInt(&buf)
        switch variant {
        
        case 1: return .light
        
        case 2: return .dark
        
        default: throw UniffiInternalError.unexpectedEnumCase
        }
    }

    public static func write(_ value: ThemeVariant, into buf: inout [UInt8]) {
        switch value {
        
        
        case .light:
            writeInt(&buf, Int32(1))
        
        
        case .dark:
            writeInt(&buf, Int32(2))
        
        }
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThemeVariant_lift(_ buf: RustBuffer) throws -> ThemeVariant {
    return try FfiConverterTypeThemeVariant.lift(buf)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeThemeVariant_lower(_ value: ThemeVariant) -> RustBuffer {
    return FfiConverterTypeThemeVariant.lower(value)
}


extension ThemeVariant: Equatable, Hashable {}






#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt32: FfiConverterRustBuffer {
    typealias SwiftType = UInt32?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt32.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt32.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionUInt64: FfiConverterRustBuffer {
    typealias SwiftType = UInt64?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterUInt64.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterUInt64.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionBool: FfiConverterRustBuffer {
    typealias SwiftType = Bool?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterBool.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterBool.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionString: FfiConverterRustBuffer {
    typealias SwiftType = String?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterString.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterString.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterOptionData: FfiConverterRustBuffer {
    typealias SwiftType = Data?

    public static func write(_ value: SwiftType, into buf: inout [UInt8]) {
        guard let value = value else {
            writeInt(&buf, Int8(0))
            return
        }
        writeInt(&buf, Int8(1))
        FfiConverterData.write(value, into: &buf)
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> SwiftType {
        switch try readInt(&buf) as Int8 {
        case 0: return nil
        case 1: return try FfiConverterData.read(from: &buf)
        default: throw UniffiInternalError.unexpectedOptionalTag
        }
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceString: FfiConverterRustBuffer {
    typealias SwiftType = [String]

    public static func write(_ value: [String], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterString.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [String] {
        let len: Int32 = try readInt(&buf)
        var seq = [String]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterString.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeTxPayloadExtension: FfiConverterRustBuffer {
    typealias SwiftType = [TxPayloadExtension]

    public static func write(_ value: [TxPayloadExtension], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeTxPayloadExtension.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [TxPayloadExtension] {
        let len: Int32 = try readInt(&buf)
        var seq = [TxPayloadExtension]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeTxPayloadExtension.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeVrfTranscriptItem: FfiConverterRustBuffer {
    typealias SwiftType = [VrfTranscriptItem]

    public static func write(_ value: [VrfTranscriptItem], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeVrfTranscriptItem.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [VrfTranscriptItem] {
        let len: Int32 = try readInt(&buf)
        var seq = [VrfTranscriptItem]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeVrfTranscriptItem.read(from: &buf))
        }
        return seq
    }
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
fileprivate struct FfiConverterSequenceTypeRingLocationJunction: FfiConverterRustBuffer {
    typealias SwiftType = [RingLocationJunction]

    public static func write(_ value: [RingLocationJunction], into buf: inout [UInt8]) {
        let len = Int32(value.count)
        writeInt(&buf, len)
        for item in value {
            FfiConverterTypeRingLocationJunction.write(item, into: &buf)
        }
    }

    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> [RingLocationJunction] {
        let len: Int32 = try readInt(&buf)
        var seq = [RingLocationJunction]()
        seq.reserveCapacity(Int(len))
        for _ in 0 ..< len {
            seq.append(try FfiConverterTypeRingLocationJunction.read(from: &buf))
        }
        return seq
    }
}


/**
 * Typealias from the type name used in the UDL file to the builtin type.  This
 * is needed because the UDL type name is used in function/method signatures.
 */
public typealias Bytes32 = Data

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public struct FfiConverterTypeBytes32: FfiConverter {
    public static func read(from buf: inout (data: Data, offset: Data.Index)) throws -> Bytes32 {
        return try FfiConverterData.read(from: &buf)
    }

    public static func write(_ value: Bytes32, into buf: inout [UInt8]) {
        return FfiConverterData.write(value, into: &buf)
    }

    public static func lift(_ value: RustBuffer) throws -> Bytes32 {
        return try FfiConverterData.lift(value)
    }

    public static func lower(_ value: Bytes32) -> RustBuffer {
        return FfiConverterData.lower(value)
    }
}


#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBytes32_lift(_ value: RustBuffer) throws -> Bytes32 {
    return try FfiConverterTypeBytes32.lift(value)
}

#if swift(>=5.8)
@_documentation(visibility: private)
#endif
public func FfiConverterTypeBytes32_lower(_ value: Bytes32) -> RustBuffer {
    return FfiConverterTypeBytes32.lower(value)
}


private enum InitializationResult {
    case ok
    case contractVersionMismatch
    case apiChecksumMismatch
}
// Use a global variable to perform the versioning checks. Swift ensures that
// the code inside is only computed once.
private let initializationResult: InitializationResult = {
    // Get the bindings contract version from our ComponentInterface
    let bindings_contract_version = 29
    // Get the scaffolding contract version by calling the into the dylib
    let scaffolding_contract_version = ffi_truapi_uniffi_contract_version()
    if bindings_contract_version != scaffolding_contract_version {
        return InitializationResult.contractVersionMismatch
    }

    return InitializationResult.ok
}()

// Make the ensure init function public so that other modules which have external type references to
// our types can call it.
public func uniffiEnsureTruapiInitialized() {
    switch initializationResult {
    case .ok:
        break
    case .contractVersionMismatch:
        fatalError("UniFFI contract version mismatch: try cleaning and rebuilding your project")
    case .apiChecksumMismatch:
        fatalError("UniFFI API checksum mismatch: try cleaning and rebuilding your project")
    }
}

// swiftlint:enable all