// This file was autogenerated by some hot garbage in the `uniffi` crate.
// Trust me, you don't want to mess with it!

#pragma once

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The following structs are used to implement the lowest level
// of the FFI, and thus useful to multiple uniffied crates.
// We ensure they are declared exactly once, with a header guard, UNIFFI_SHARED_H.
#ifdef UNIFFI_SHARED_H
    // We also try to prevent mixing versions of shared uniffi header structs.
    // If you add anything to the #else block, you must increment the version suffix in UNIFFI_SHARED_HEADER_V4
    #ifndef UNIFFI_SHARED_HEADER_V4
        #error Combining helper code from multiple versions of uniffi is not supported
    #endif // ndef UNIFFI_SHARED_HEADER_V4
#else
#define UNIFFI_SHARED_H
#define UNIFFI_SHARED_HEADER_V4
// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️

typedef struct RustBuffer
{
    uint64_t capacity;
    uint64_t len;
    uint8_t *_Nullable data;
} RustBuffer;

typedef struct ForeignBytes
{
    int32_t len;
    const uint8_t *_Nullable data;
} ForeignBytes;

// Error definitions
typedef struct RustCallStatus {
    int8_t code;
    RustBuffer errorBuf;
} RustCallStatus;

// ⚠️ Attention: If you change this #else block (ending in `#endif // def UNIFFI_SHARED_H`) you *must* ⚠️
// ⚠️ increment the version suffix in all instances of UNIFFI_SHARED_HEADER_V4 in this file.           ⚠️
#endif // def UNIFFI_SHARED_H
#ifndef UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
#define UNIFFI_FFIDEF_RUST_FUTURE_CONTINUATION_CALLBACK
typedef void (*UniffiRustFutureContinuationCallback)(uint64_t, int8_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_FREE
typedef void (*UniffiForeignFutureFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_FREE
typedef void (*UniffiCallbackInterfaceFree)(uint64_t
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE
#define UNIFFI_FFIDEF_FOREIGN_FUTURE
typedef struct UniffiForeignFuture {
    uint64_t handle;
    UniffiForeignFutureFree _Nonnull free;
} UniffiForeignFuture;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U8
typedef struct UniffiForeignFutureStructU8 {
    uint8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U8
typedef void (*UniffiForeignFutureCompleteU8)(uint64_t, UniffiForeignFutureStructU8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I8
typedef struct UniffiForeignFutureStructI8 {
    int8_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI8;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I8
typedef void (*UniffiForeignFutureCompleteI8)(uint64_t, UniffiForeignFutureStructI8
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U16
typedef struct UniffiForeignFutureStructU16 {
    uint16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U16
typedef void (*UniffiForeignFutureCompleteU16)(uint64_t, UniffiForeignFutureStructU16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I16
typedef struct UniffiForeignFutureStructI16 {
    int16_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI16;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I16
typedef void (*UniffiForeignFutureCompleteI16)(uint64_t, UniffiForeignFutureStructI16
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U32
typedef struct UniffiForeignFutureStructU32 {
    uint32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U32
typedef void (*UniffiForeignFutureCompleteU32)(uint64_t, UniffiForeignFutureStructU32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I32
typedef struct UniffiForeignFutureStructI32 {
    int32_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I32
typedef void (*UniffiForeignFutureCompleteI32)(uint64_t, UniffiForeignFutureStructI32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_U64
typedef struct UniffiForeignFutureStructU64 {
    uint64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructU64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_U64
typedef void (*UniffiForeignFutureCompleteU64)(uint64_t, UniffiForeignFutureStructU64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_I64
typedef struct UniffiForeignFutureStructI64 {
    int64_t returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructI64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_I64
typedef void (*UniffiForeignFutureCompleteI64)(uint64_t, UniffiForeignFutureStructI64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F32
typedef struct UniffiForeignFutureStructF32 {
    float returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF32;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F32
typedef void (*UniffiForeignFutureCompleteF32)(uint64_t, UniffiForeignFutureStructF32
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_F64
typedef struct UniffiForeignFutureStructF64 {
    double returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructF64;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_F64
typedef void (*UniffiForeignFutureCompleteF64)(uint64_t, UniffiForeignFutureStructF64
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_POINTER
typedef struct UniffiForeignFutureStructPointer {
    void*_Nonnull returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructPointer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_POINTER
typedef void (*UniffiForeignFutureCompletePointer)(uint64_t, UniffiForeignFutureStructPointer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_RUST_BUFFER
typedef struct UniffiForeignFutureStructRustBuffer {
    RustBuffer returnValue;
    RustCallStatus callStatus;
} UniffiForeignFutureStructRustBuffer;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_RUST_BUFFER
typedef void (*UniffiForeignFutureCompleteRustBuffer)(uint64_t, UniffiForeignFutureStructRustBuffer
    );

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_STRUCT_VOID
typedef struct UniffiForeignFutureStructVoid {
    RustCallStatus callStatus;
} UniffiForeignFutureStructVoid;

#endif
#ifndef UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FOREIGN_FUTURE_COMPLETE_VOID
typedef void (*UniffiForeignFutureCompleteVoid)(uint64_t, UniffiForeignFutureStructVoid
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_NATIVE_CUSTOM_RENDERER_OBSERVER_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_NATIVE_CUSTOM_RENDERER_OBSERVER_METHOD0
typedef void (*UniffiCallbackInterfaceNativeCustomRendererObserverMethod0)(uint64_t, void*_Nonnull, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_NATIVE_CUSTOM_RENDERER_OBSERVER_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_NATIVE_CUSTOM_RENDERER_OBSERVER_METHOD1
typedef void (*UniffiCallbackInterfaceNativeCustomRendererObserverMethod1)(uint64_t, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD0
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD0
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod0)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD1
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD1
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod1)(uint64_t, RustBuffer, UniffiForeignFutureCompleteVoid _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD2
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD2
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod2)(uint64_t, RustBuffer, UniffiForeignFutureCompleteU32 _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD3
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD3
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod3)(uint64_t, uint32_t, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD4
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD4
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod4)(uint64_t, RustBuffer, UniffiForeignFutureCompleteI8 _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD5
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD5
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod5)(uint64_t, RustBuffer, UniffiForeignFutureCompleteI8 _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD6
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD6
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod6)(uint64_t, RustBuffer, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD7
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD7
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod7)(uint64_t, RustBuffer, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD8
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD8
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod8)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD9
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD9
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod9)(uint64_t, RustBuffer, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD10
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD10
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod10)(uint64_t, RustBuffer, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD11
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD11
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod11)(uint64_t, uint32_t, RustBuffer, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD12
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD12
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod12)(uint64_t, uint32_t, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD13
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD13
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod13)(uint64_t, RustBuffer, UniffiForeignFutureCompleteI8 _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD14
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD14
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod14)(uint64_t, RustBuffer, UniffiForeignFutureCompleteRustBuffer _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD15
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD15
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod15)(uint64_t, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD16
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD16
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod16)(uint64_t, RustBuffer, UniffiForeignFutureCompleteI8 _Nonnull, uint64_t, UniffiForeignFuture* _Nonnull
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD17
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD17
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod17)(uint64_t, RustBuffer, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD18
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD18
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod18)(uint64_t, RustBuffer, RustBuffer, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD19
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD19
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod19)(uint64_t, RustBuffer, void* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD20
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD20
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod20)(uint64_t, int8_t* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD21
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD21
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod21)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD22
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD22
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod22)(uint64_t, RustBuffer, RustBuffer, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD23
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD23
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod23)(uint64_t, RustBuffer, RustBuffer, RustBuffer, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD24
#define UNIFFI_FFIDEF_CALLBACK_INTERFACE_HOST_CALLBACKS_METHOD24
typedef void (*UniffiCallbackInterfaceHostCallbacksMethod24)(uint64_t, RustBuffer* _Nonnull,
        RustCallStatus *_Nonnull uniffiCallStatus
    );

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_NATIVE_CUSTOM_RENDERER_OBSERVER
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_NATIVE_CUSTOM_RENDERER_OBSERVER
typedef struct UniffiVTableCallbackInterfaceNativeCustomRendererObserver {
    UniffiCallbackInterfaceNativeCustomRendererObserverMethod0 _Nonnull onUpdate;
    UniffiCallbackInterfaceNativeCustomRendererObserverMethod1 _Nonnull onComplete;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceNativeCustomRendererObserver;

#endif
#ifndef UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_HOST_CALLBACKS
#define UNIFFI_FFIDEF_V_TABLE_CALLBACK_INTERFACE_HOST_CALLBACKS
typedef struct UniffiVTableCallbackInterfaceHostCallbacks {
    UniffiCallbackInterfaceHostCallbacksMethod0 _Nonnull onCoreLog;
    UniffiCallbackInterfaceHostCallbacksMethod1 _Nonnull navigateTo;
    UniffiCallbackInterfaceHostCallbacksMethod2 _Nonnull pushNotification;
    UniffiCallbackInterfaceHostCallbacksMethod3 _Nonnull cancelNotification;
    UniffiCallbackInterfaceHostCallbacksMethod4 _Nonnull devicePermission;
    UniffiCallbackInterfaceHostCallbacksMethod5 _Nonnull remotePermission;
    UniffiCallbackInterfaceHostCallbacksMethod6 _Nonnull authStateChanged;
    UniffiCallbackInterfaceHostCallbacksMethod7 _Nonnull coreStorageRead;
    UniffiCallbackInterfaceHostCallbacksMethod8 _Nonnull coreStorageWrite;
    UniffiCallbackInterfaceHostCallbacksMethod9 _Nonnull coreStorageClear;
    UniffiCallbackInterfaceHostCallbacksMethod10 _Nonnull chainConnect;
    UniffiCallbackInterfaceHostCallbacksMethod11 _Nonnull chainSend;
    UniffiCallbackInterfaceHostCallbacksMethod12 _Nonnull chainClose;
    UniffiCallbackInterfaceHostCallbacksMethod13 _Nonnull confirmUserAction;
    UniffiCallbackInterfaceHostCallbacksMethod14 _Nonnull lookupPreimage;
    UniffiCallbackInterfaceHostCallbacksMethod15 _Nonnull currentTheme;
    UniffiCallbackInterfaceHostCallbacksMethod16 _Nonnull featureSupported;
    UniffiCallbackInterfaceHostCallbacksMethod17 _Nonnull localStorageRead;
    UniffiCallbackInterfaceHostCallbacksMethod18 _Nonnull localStorageWrite;
    UniffiCallbackInterfaceHostCallbacksMethod19 _Nonnull localStorageClear;
    UniffiCallbackInterfaceHostCallbacksMethod20 _Nonnull chatSupported;
    UniffiCallbackInterfaceHostCallbacksMethod21 _Nonnull chatCreateRoom;
    UniffiCallbackInterfaceHostCallbacksMethod22 _Nonnull chatPostTextMessage;
    UniffiCallbackInterfaceHostCallbacksMethod23 _Nonnull chatPostCustomMessage;
    UniffiCallbackInterfaceHostCallbacksMethod24 _Nonnull chatListRooms;
    UniffiCallbackInterfaceFree _Nonnull uniffiFree;
} UniffiVTableCallbackInterfaceHostCallbacks;

#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_HOSTCALLBACKS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_HOSTCALLBACKS
void*_Nonnull uniffi_truapi_server_fn_clone_hostcallbacks(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_HOSTCALLBACKS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_HOSTCALLBACKS
void uniffi_truapi_server_fn_free_hostcallbacks(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_INIT_CALLBACK_VTABLE_HOSTCALLBACKS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_INIT_CALLBACK_VTABLE_HOSTCALLBACKS
void uniffi_truapi_server_fn_init_callback_vtable_hostcallbacks(const UniffiVTableCallbackInterfaceHostCallbacks* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_ON_CORE_LOG
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_ON_CORE_LOG
void uniffi_truapi_server_fn_method_hostcallbacks_on_core_log(void*_Nonnull ptr, RustBuffer marker, RustBuffer detail, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_NAVIGATE_TO
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_NAVIGATE_TO
uint64_t uniffi_truapi_server_fn_method_hostcallbacks_navigate_to(void*_Nonnull ptr, RustBuffer url
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_PUSH_NOTIFICATION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_PUSH_NOTIFICATION
uint64_t uniffi_truapi_server_fn_method_hostcallbacks_push_notification(void*_Nonnull ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CANCEL_NOTIFICATION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CANCEL_NOTIFICATION
void uniffi_truapi_server_fn_method_hostcallbacks_cancel_notification(void*_Nonnull ptr, uint32_t id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_DEVICE_PERMISSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_DEVICE_PERMISSION
uint64_t uniffi_truapi_server_fn_method_hostcallbacks_device_permission(void*_Nonnull ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_REMOTE_PERMISSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_REMOTE_PERMISSION
uint64_t uniffi_truapi_server_fn_method_hostcallbacks_remote_permission(void*_Nonnull ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_AUTH_STATE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_AUTH_STATE_CHANGED
void uniffi_truapi_server_fn_method_hostcallbacks_auth_state_changed(void*_Nonnull ptr, RustBuffer state, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CORE_STORAGE_READ
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CORE_STORAGE_READ
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_core_storage_read(void*_Nonnull ptr, RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CORE_STORAGE_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CORE_STORAGE_WRITE
void uniffi_truapi_server_fn_method_hostcallbacks_core_storage_write(void*_Nonnull ptr, RustBuffer key, RustBuffer value, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CORE_STORAGE_CLEAR
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CORE_STORAGE_CLEAR
void uniffi_truapi_server_fn_method_hostcallbacks_core_storage_clear(void*_Nonnull ptr, RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAIN_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAIN_CONNECT
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_chain_connect(void*_Nonnull ptr, RustBuffer genesis_hash, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAIN_SEND
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAIN_SEND
void uniffi_truapi_server_fn_method_hostcallbacks_chain_send(void*_Nonnull ptr, uint32_t connection_id, RustBuffer request, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAIN_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAIN_CLOSE
void uniffi_truapi_server_fn_method_hostcallbacks_chain_close(void*_Nonnull ptr, uint32_t connection_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CONFIRM_USER_ACTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CONFIRM_USER_ACTION
uint64_t uniffi_truapi_server_fn_method_hostcallbacks_confirm_user_action(void*_Nonnull ptr, RustBuffer review
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOOKUP_PREIMAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOOKUP_PREIMAGE
uint64_t uniffi_truapi_server_fn_method_hostcallbacks_lookup_preimage(void*_Nonnull ptr, RustBuffer key
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CURRENT_THEME
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CURRENT_THEME
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_current_theme(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_FEATURE_SUPPORTED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_FEATURE_SUPPORTED
uint64_t uniffi_truapi_server_fn_method_hostcallbacks_feature_supported(void*_Nonnull ptr, RustBuffer request
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_READ
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_READ
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_local_storage_read(void*_Nonnull ptr, RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_WRITE
void uniffi_truapi_server_fn_method_hostcallbacks_local_storage_write(void*_Nonnull ptr, RustBuffer key, RustBuffer value, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_CLEAR
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_CLEAR
void uniffi_truapi_server_fn_method_hostcallbacks_local_storage_clear(void*_Nonnull ptr, RustBuffer key, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_SUPPORTED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_SUPPORTED
int8_t uniffi_truapi_server_fn_method_hostcallbacks_chat_supported(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_CREATE_ROOM
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_CREATE_ROOM
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_chat_create_room(void*_Nonnull ptr, RustBuffer room_id, RustBuffer name, RustBuffer icon, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_POST_TEXT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_POST_TEXT_MESSAGE
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_chat_post_text_message(void*_Nonnull ptr, RustBuffer room_id, RustBuffer text, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_POST_CUSTOM_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_POST_CUSTOM_MESSAGE
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_chat_post_custom_message(void*_Nonnull ptr, RustBuffer room_id, RustBuffer message_type, RustBuffer payload, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_LIST_ROOMS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_HOSTCALLBACKS_CHAT_LIST_ROOMS
RustBuffer uniffi_truapi_server_fn_method_hostcallbacks_chat_list_rooms(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVECUSTOMRENDERERNODE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVECUSTOMRENDERERNODE
void*_Nonnull uniffi_truapi_server_fn_clone_nativecustomrenderernode(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVECUSTOMRENDERERNODE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVECUSTOMRENDERERNODE
void uniffi_truapi_server_fn_free_nativecustomrenderernode(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_BOX_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_BOX_PROPS
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_box_props(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_BUTTON_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_BUTTON_PROPS
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_button_props(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_CHILDREN
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_CHILDREN
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_children(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_COLUMN_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_COLUMN_PROPS
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_column_props(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_KIND
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_KIND
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_kind(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_MODIFIERS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_MODIFIERS
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_modifiers(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_ROW_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_ROW_PROPS
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_row_props(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_STRING_TEXT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_STRING_TEXT
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_string_text(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_FIELD_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_FIELD_PROPS
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_text_field_props(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_PROPS
RustBuffer uniffi_truapi_server_fn_method_nativecustomrenderernode_text_props(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVECUSTOMRENDERERSUBSCRIPTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVECUSTOMRENDERERSUBSCRIPTION
void*_Nonnull uniffi_truapi_server_fn_clone_nativecustomrenderersubscription(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVECUSTOMRENDERERSUBSCRIPTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVECUSTOMRENDERERSUBSCRIPTION
void uniffi_truapi_server_fn_free_nativecustomrenderersubscription(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERSUBSCRIPTION_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVECUSTOMRENDERERSUBSCRIPTION_CANCEL
void uniffi_truapi_server_fn_method_nativecustomrenderersubscription_cancel(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVEPRODUCTEXECUTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVEPRODUCTEXECUTION
void*_Nonnull uniffi_truapi_server_fn_clone_nativeproductexecution(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVEPRODUCTEXECUTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVEPRODUCTEXECUTION
void uniffi_truapi_server_fn_free_nativeproductexecution(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_CLOSE
void uniffi_truapi_server_fn_method_nativeproductexecution_close(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_CLOSED
void uniffi_truapi_server_fn_method_nativeproductexecution_notify_chain_closed(void*_Nonnull ptr, uint32_t connection_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_RESPONSE
void uniffi_truapi_server_fn_method_nativeproductexecution_notify_chain_response(void*_Nonnull ptr, uint32_t connection_id, RustBuffer json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAT_ROOMS_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAT_ROOMS_CHANGED
void uniffi_truapi_server_fn_method_nativeproductexecution_notify_chat_rooms_changed(void*_Nonnull ptr, RustBuffer rooms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_PREIMAGE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_PREIMAGE_CHANGED
void uniffi_truapi_server_fn_method_nativeproductexecution_notify_preimage_changed(void*_Nonnull ptr, RustBuffer key, RustBuffer value, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_THEME_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_THEME_CHANGED
void uniffi_truapi_server_fn_method_nativeproductexecution_notify_theme_changed(void*_Nonnull ptr, RustBuffer theme, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_PERMISSION_AUTHORIZATION_STATUS
RustBuffer uniffi_truapi_server_fn_method_nativeproductexecution_permission_authorization_status(void*_Nonnull ptr, RustBuffer request, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_PUBLISH_CHAT_ACTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_PUBLISH_CHAT_ACTION
void uniffi_truapi_server_fn_method_nativeproductexecution_publish_chat_action(void*_Nonnull ptr, RustBuffer action, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_RENDER_CUSTOM_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_RENDER_CUSTOM_MESSAGE
void*_Nonnull uniffi_truapi_server_fn_method_nativeproductexecution_render_custom_message(void*_Nonnull ptr, RustBuffer message_id, RustBuffer message_type, RustBuffer payload, uint64_t observer, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_SET_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_SET_PERMISSION_AUTHORIZATION_STATUS
void uniffi_truapi_server_fn_method_nativeproductexecution_set_permission_authorization_status(void*_Nonnull ptr, RustBuffer request, RustBuffer status, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_START_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_START_WS_BRIDGE
RustBuffer uniffi_truapi_server_fn_method_nativeproductexecution_start_ws_bridge(void*_Nonnull ptr, uint16_t bind_port, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_STOP_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVEPRODUCTEXECUTION_STOP_WS_BRIDGE
void uniffi_truapi_server_fn_method_nativeproductexecution_stop_ws_bridge(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVETRUAPICORE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVETRUAPICORE
void*_Nonnull uniffi_truapi_server_fn_clone_nativetruapicore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVETRUAPICORE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVETRUAPICORE
void uniffi_truapi_server_fn_free_nativetruapicore(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CONSTRUCTOR_NATIVETRUAPICORE_WITH_RUNTIME_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CONSTRUCTOR_NATIVETRUAPICORE_WITH_RUNTIME_CONFIG
void*_Nonnull uniffi_truapi_server_fn_constructor_nativetruapicore_with_runtime_config(void*_Nonnull callbacks, RustBuffer runtime_config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_ACTIVATE_LOCAL_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_ACTIVATE_LOCAL_SESSION
void uniffi_truapi_server_fn_method_nativetruapicore_activate_local_session(void*_Nonnull ptr, RustBuffer secret, RustBuffer lite_username, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_CANCEL_LOGIN
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_CANCEL_LOGIN
void uniffi_truapi_server_fn_method_nativetruapicore_cancel_login(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_DISCONNECT
void uniffi_truapi_server_fn_method_nativetruapicore_disconnect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_CLOSED
void uniffi_truapi_server_fn_method_nativetruapicore_notify_chain_closed(void*_Nonnull ptr, uint32_t connection_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_RESPONSE
void uniffi_truapi_server_fn_method_nativetruapicore_notify_chain_response(void*_Nonnull ptr, uint32_t connection_id, RustBuffer json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_CHAT_ROOMS_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_CHAT_ROOMS_CHANGED
void uniffi_truapi_server_fn_method_nativetruapicore_notify_chat_rooms_changed(void*_Nonnull ptr, RustBuffer rooms, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_PREIMAGE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_PREIMAGE_CHANGED
void uniffi_truapi_server_fn_method_nativetruapicore_notify_preimage_changed(void*_Nonnull ptr, RustBuffer key, RustBuffer value, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_SESSION_STORE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_SESSION_STORE_CHANGED
void uniffi_truapi_server_fn_method_nativetruapicore_notify_session_store_changed(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_THEME_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_NOTIFY_THEME_CHANGED
void uniffi_truapi_server_fn_method_nativetruapicore_notify_theme_changed(void*_Nonnull ptr, RustBuffer theme, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_PERMISSION_AUTHORIZATION_STATUS
RustBuffer uniffi_truapi_server_fn_method_nativetruapicore_permission_authorization_status(void*_Nonnull ptr, RustBuffer request, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_PUBLISH_CHAT_ACTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_PUBLISH_CHAT_ACTION
void uniffi_truapi_server_fn_method_nativetruapicore_publish_chat_action(void*_Nonnull ptr, RustBuffer action, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_RENDER_CUSTOM_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_RENDER_CUSTOM_MESSAGE
void*_Nonnull uniffi_truapi_server_fn_method_nativetruapicore_render_custom_message(void*_Nonnull ptr, RustBuffer message_id, RustBuffer message_type, RustBuffer payload, uint64_t observer, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_SET_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_SET_PERMISSION_AUTHORIZATION_STATUS
void uniffi_truapi_server_fn_method_nativetruapicore_set_permission_authorization_status(void*_Nonnull ptr, RustBuffer request, RustBuffer status, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
RustBuffer uniffi_truapi_server_fn_method_nativetruapicore_start_ws_bridge(void*_Nonnull ptr, uint16_t bind_port, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
void uniffi_truapi_server_fn_method_nativetruapicore_stop_ws_bridge(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVETRUAPIHOSTRUNTIME
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CLONE_NATIVETRUAPIHOSTRUNTIME
void*_Nonnull uniffi_truapi_server_fn_clone_nativetruapihostruntime(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVETRUAPIHOSTRUNTIME
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FREE_NATIVETRUAPIHOSTRUNTIME
void uniffi_truapi_server_fn_free_nativetruapihostruntime(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CONSTRUCTOR_NATIVETRUAPIHOSTRUNTIME_WITH_RUNTIME_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_CONSTRUCTOR_NATIVETRUAPIHOSTRUNTIME_WITH_RUNTIME_CONFIG
void*_Nonnull uniffi_truapi_server_fn_constructor_nativetruapihostruntime_with_runtime_config(void*_Nonnull callbacks, RustBuffer runtime_config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_ACTIVATE_LOCAL_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_ACTIVATE_LOCAL_SESSION
void uniffi_truapi_server_fn_method_nativetruapihostruntime_activate_local_session(void*_Nonnull ptr, RustBuffer secret, RustBuffer lite_username, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_CANCEL_LOGIN
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_CANCEL_LOGIN
void uniffi_truapi_server_fn_method_nativetruapihostruntime_cancel_login(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_DISCONNECT
void uniffi_truapi_server_fn_method_nativetruapihostruntime_disconnect(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_CLOSED
void uniffi_truapi_server_fn_method_nativetruapihostruntime_notify_chain_closed(void*_Nonnull ptr, uint32_t connection_id, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_RESPONSE
void uniffi_truapi_server_fn_method_nativetruapihostruntime_notify_chain_response(void*_Nonnull ptr, uint32_t connection_id, RustBuffer json, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_SESSION_STORE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_SESSION_STORE_CHANGED
void uniffi_truapi_server_fn_method_nativetruapihostruntime_notify_session_store_changed(void*_Nonnull ptr, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_OPEN_PRODUCT_EXECUTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_METHOD_NATIVETRUAPIHOSTRUNTIME_OPEN_PRODUCT_EXECUTION
void*_Nonnull uniffi_truapi_server_fn_method_nativetruapihostruntime_open_product_execution(void*_Nonnull ptr, void*_Nonnull callbacks, RustBuffer execution_config, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_INIT_CALLBACK_VTABLE_NATIVECUSTOMRENDEREROBSERVER
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_INIT_CALLBACK_VTABLE_NATIVECUSTOMRENDEREROBSERVER
void uniffi_truapi_server_fn_init_callback_vtable_nativecustomrendererobserver(const UniffiVTableCallbackInterfaceNativeCustomRendererObserver* _Nonnull vtable
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FUNC_PARSE_NAVIGATE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FUNC_PARSE_NAVIGATE
RustBuffer uniffi_truapi_server_fn_func_parse_navigate(RustBuffer input, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FUNC_SET_LOG_LEVEL
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_FN_FUNC_SET_LOG_LEVEL
void uniffi_truapi_server_fn_func_set_log_level(RustBuffer level, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_ALLOC
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_ALLOC
RustBuffer ffi_truapi_server_rustbuffer_alloc(uint64_t size, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FROM_BYTES
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FROM_BYTES
RustBuffer ffi_truapi_server_rustbuffer_from_bytes(ForeignBytes bytes, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FREE
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_FREE
void ffi_truapi_server_rustbuffer_free(RustBuffer buf, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_RESERVE
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUSTBUFFER_RESERVE
RustBuffer ffi_truapi_server_rustbuffer_reserve(RustBuffer buf, uint64_t additional, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U8
void ffi_truapi_server_rust_future_poll_u8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U8
void ffi_truapi_server_rust_future_cancel_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U8
void ffi_truapi_server_rust_future_free_u8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U8
uint8_t ffi_truapi_server_rust_future_complete_u8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I8
void ffi_truapi_server_rust_future_poll_i8(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I8
void ffi_truapi_server_rust_future_cancel_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I8
void ffi_truapi_server_rust_future_free_i8(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I8
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I8
int8_t ffi_truapi_server_rust_future_complete_i8(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U16
void ffi_truapi_server_rust_future_poll_u16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U16
void ffi_truapi_server_rust_future_cancel_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U16
void ffi_truapi_server_rust_future_free_u16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U16
uint16_t ffi_truapi_server_rust_future_complete_u16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I16
void ffi_truapi_server_rust_future_poll_i16(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I16
void ffi_truapi_server_rust_future_cancel_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I16
void ffi_truapi_server_rust_future_free_i16(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I16
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I16
int16_t ffi_truapi_server_rust_future_complete_i16(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U32
void ffi_truapi_server_rust_future_poll_u32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U32
void ffi_truapi_server_rust_future_cancel_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U32
void ffi_truapi_server_rust_future_free_u32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U32
uint32_t ffi_truapi_server_rust_future_complete_u32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I32
void ffi_truapi_server_rust_future_poll_i32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I32
void ffi_truapi_server_rust_future_cancel_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I32
void ffi_truapi_server_rust_future_free_i32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I32
int32_t ffi_truapi_server_rust_future_complete_i32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_U64
void ffi_truapi_server_rust_future_poll_u64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_U64
void ffi_truapi_server_rust_future_cancel_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_U64
void ffi_truapi_server_rust_future_free_u64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_U64
uint64_t ffi_truapi_server_rust_future_complete_u64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_I64
void ffi_truapi_server_rust_future_poll_i64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_I64
void ffi_truapi_server_rust_future_cancel_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_I64
void ffi_truapi_server_rust_future_free_i64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_I64
int64_t ffi_truapi_server_rust_future_complete_i64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F32
void ffi_truapi_server_rust_future_poll_f32(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F32
void ffi_truapi_server_rust_future_cancel_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F32
void ffi_truapi_server_rust_future_free_f32(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F32
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F32
float ffi_truapi_server_rust_future_complete_f32(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_F64
void ffi_truapi_server_rust_future_poll_f64(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_F64
void ffi_truapi_server_rust_future_cancel_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_F64
void ffi_truapi_server_rust_future_free_f64(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F64
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_F64
double ffi_truapi_server_rust_future_complete_f64(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_POINTER
void ffi_truapi_server_rust_future_poll_pointer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_POINTER
void ffi_truapi_server_rust_future_cancel_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_POINTER
void ffi_truapi_server_rust_future_free_pointer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_POINTER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_POINTER
void*_Nonnull ffi_truapi_server_rust_future_complete_pointer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_RUST_BUFFER
void ffi_truapi_server_rust_future_poll_rust_buffer(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_RUST_BUFFER
void ffi_truapi_server_rust_future_cancel_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_RUST_BUFFER
void ffi_truapi_server_rust_future_free_rust_buffer(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_RUST_BUFFER
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_RUST_BUFFER
RustBuffer ffi_truapi_server_rust_future_complete_rust_buffer(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_POLL_VOID
void ffi_truapi_server_rust_future_poll_void(uint64_t handle, UniffiRustFutureContinuationCallback _Nonnull callback, uint64_t callback_data
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_CANCEL_VOID
void ffi_truapi_server_rust_future_cancel_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_FREE_VOID
void ffi_truapi_server_rust_future_free_void(uint64_t handle
);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_VOID
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_RUST_FUTURE_COMPLETE_VOID
void ffi_truapi_server_rust_future_complete_void(uint64_t handle, RustCallStatus *_Nonnull out_status
);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_FUNC_PARSE_NAVIGATE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_FUNC_PARSE_NAVIGATE
uint16_t uniffi_truapi_server_checksum_func_parse_navigate(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_FUNC_SET_LOG_LEVEL
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_FUNC_SET_LOG_LEVEL
uint16_t uniffi_truapi_server_checksum_func_set_log_level(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_ON_CORE_LOG
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_ON_CORE_LOG
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_on_core_log(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_NAVIGATE_TO
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_NAVIGATE_TO
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_navigate_to(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_PUSH_NOTIFICATION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_PUSH_NOTIFICATION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_push_notification(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CANCEL_NOTIFICATION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CANCEL_NOTIFICATION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_cancel_notification(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_DEVICE_PERMISSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_DEVICE_PERMISSION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_device_permission(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_REMOTE_PERMISSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_REMOTE_PERMISSION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_remote_permission(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_AUTH_STATE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_AUTH_STATE_CHANGED
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_auth_state_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CORE_STORAGE_READ
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CORE_STORAGE_READ
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_core_storage_read(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CORE_STORAGE_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CORE_STORAGE_WRITE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_core_storage_write(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CORE_STORAGE_CLEAR
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CORE_STORAGE_CLEAR
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_core_storage_clear(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAIN_CONNECT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAIN_CONNECT
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chain_connect(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAIN_SEND
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAIN_SEND
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chain_send(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAIN_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAIN_CLOSE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chain_close(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CONFIRM_USER_ACTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CONFIRM_USER_ACTION
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_confirm_user_action(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOOKUP_PREIMAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOOKUP_PREIMAGE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_lookup_preimage(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CURRENT_THEME
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CURRENT_THEME
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_current_theme(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_FEATURE_SUPPORTED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_FEATURE_SUPPORTED
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_feature_supported(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_READ
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_READ
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_local_storage_read(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_WRITE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_WRITE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_local_storage_write(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_CLEAR
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_LOCAL_STORAGE_CLEAR
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_local_storage_clear(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_SUPPORTED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_SUPPORTED
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chat_supported(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_CREATE_ROOM
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_CREATE_ROOM
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chat_create_room(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_POST_TEXT_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_POST_TEXT_MESSAGE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chat_post_text_message(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_POST_CUSTOM_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_POST_CUSTOM_MESSAGE
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chat_post_custom_message(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_LIST_ROOMS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_HOSTCALLBACKS_CHAT_LIST_ROOMS
uint16_t uniffi_truapi_server_checksum_method_hostcallbacks_chat_list_rooms(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_BOX_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_BOX_PROPS
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_box_props(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_BUTTON_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_BUTTON_PROPS
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_button_props(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_CHILDREN
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_CHILDREN
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_children(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_COLUMN_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_COLUMN_PROPS
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_column_props(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_KIND
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_KIND
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_kind(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_MODIFIERS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_MODIFIERS
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_modifiers(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_ROW_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_ROW_PROPS
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_row_props(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_STRING_TEXT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_STRING_TEXT
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_string_text(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_FIELD_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_FIELD_PROPS
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_text_field_props(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_PROPS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERNODE_TEXT_PROPS
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderernode_text_props(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERSUBSCRIPTION_CANCEL
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDERERSUBSCRIPTION_CANCEL
uint16_t uniffi_truapi_server_checksum_method_nativecustomrenderersubscription_cancel(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_CLOSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_CLOSE
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_close(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_CLOSED
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_notify_chain_closed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAIN_RESPONSE
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_notify_chain_response(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAT_ROOMS_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_CHAT_ROOMS_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_notify_chat_rooms_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_PREIMAGE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_PREIMAGE_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_notify_preimage_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_THEME_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_NOTIFY_THEME_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_notify_theme_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_PERMISSION_AUTHORIZATION_STATUS
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_permission_authorization_status(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_PUBLISH_CHAT_ACTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_PUBLISH_CHAT_ACTION
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_publish_chat_action(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_RENDER_CUSTOM_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_RENDER_CUSTOM_MESSAGE
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_render_custom_message(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_SET_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_SET_PERMISSION_AUTHORIZATION_STATUS
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_set_permission_authorization_status(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_START_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_START_WS_BRIDGE
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_start_ws_bridge(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_STOP_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVEPRODUCTEXECUTION_STOP_WS_BRIDGE
uint16_t uniffi_truapi_server_checksum_method_nativeproductexecution_stop_ws_bridge(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_ACTIVATE_LOCAL_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_ACTIVATE_LOCAL_SESSION
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_activate_local_session(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_CANCEL_LOGIN
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_CANCEL_LOGIN
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_cancel_login(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_DISCONNECT
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_disconnect(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_CLOSED
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_notify_chain_closed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_CHAIN_RESPONSE
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_notify_chain_response(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_CHAT_ROOMS_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_CHAT_ROOMS_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_notify_chat_rooms_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_PREIMAGE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_PREIMAGE_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_notify_preimage_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_SESSION_STORE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_SESSION_STORE_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_notify_session_store_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_THEME_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_NOTIFY_THEME_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_notify_theme_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_PERMISSION_AUTHORIZATION_STATUS
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_permission_authorization_status(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_PUBLISH_CHAT_ACTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_PUBLISH_CHAT_ACTION
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_publish_chat_action(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_RENDER_CUSTOM_MESSAGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_RENDER_CUSTOM_MESSAGE
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_render_custom_message(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_SET_PERMISSION_AUTHORIZATION_STATUS
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_SET_PERMISSION_AUTHORIZATION_STATUS
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_set_permission_authorization_status(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_START_WS_BRIDGE
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_start_ws_bridge(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPICORE_STOP_WS_BRIDGE
uint16_t uniffi_truapi_server_checksum_method_nativetruapicore_stop_ws_bridge(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_ACTIVATE_LOCAL_SESSION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_ACTIVATE_LOCAL_SESSION
uint16_t uniffi_truapi_server_checksum_method_nativetruapihostruntime_activate_local_session(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_CANCEL_LOGIN
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_CANCEL_LOGIN
uint16_t uniffi_truapi_server_checksum_method_nativetruapihostruntime_cancel_login(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_DISCONNECT
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_DISCONNECT
uint16_t uniffi_truapi_server_checksum_method_nativetruapihostruntime_disconnect(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_CLOSED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_CLOSED
uint16_t uniffi_truapi_server_checksum_method_nativetruapihostruntime_notify_chain_closed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_RESPONSE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_CHAIN_RESPONSE
uint16_t uniffi_truapi_server_checksum_method_nativetruapihostruntime_notify_chain_response(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_SESSION_STORE_CHANGED
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_NOTIFY_SESSION_STORE_CHANGED
uint16_t uniffi_truapi_server_checksum_method_nativetruapihostruntime_notify_session_store_changed(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_OPEN_PRODUCT_EXECUTION
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVETRUAPIHOSTRUNTIME_OPEN_PRODUCT_EXECUTION
uint16_t uniffi_truapi_server_checksum_method_nativetruapihostruntime_open_product_execution(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_CONSTRUCTOR_NATIVETRUAPICORE_WITH_RUNTIME_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_CONSTRUCTOR_NATIVETRUAPICORE_WITH_RUNTIME_CONFIG
uint16_t uniffi_truapi_server_checksum_constructor_nativetruapicore_with_runtime_config(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_CONSTRUCTOR_NATIVETRUAPIHOSTRUNTIME_WITH_RUNTIME_CONFIG
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_CONSTRUCTOR_NATIVETRUAPIHOSTRUNTIME_WITH_RUNTIME_CONFIG
uint16_t uniffi_truapi_server_checksum_constructor_nativetruapihostruntime_with_runtime_config(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDEREROBSERVER_ON_UPDATE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDEREROBSERVER_ON_UPDATE
uint16_t uniffi_truapi_server_checksum_method_nativecustomrendererobserver_on_update(void

);
#endif
#ifndef UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDEREROBSERVER_ON_COMPLETE
#define UNIFFI_FFIDEF_UNIFFI_TRUAPI_SERVER_CHECKSUM_METHOD_NATIVECUSTOMRENDEREROBSERVER_ON_COMPLETE
uint16_t uniffi_truapi_server_checksum_method_nativecustomrendererobserver_on_complete(void

);
#endif
#ifndef UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_UNIFFI_CONTRACT_VERSION
#define UNIFFI_FFIDEF_FFI_TRUAPI_SERVER_UNIFFI_CONTRACT_VERSION
uint32_t ffi_truapi_server_uniffi_contract_version(void

);
#endif

