// Auto-generated by truapi-codegen. Do not edit.
//
// Adapts the typed `HostCallbacks` surface onto the byte-oriented
// callback surface the WASM core invokes. Codec-backed wire and
// platform-local types cross as SCALE bytes (`.enc`/`.dec`); strings,
// primitives and byte blobs pass through unchanged.

import {
  HostChatCreateRoomRequest,
  HostChatCreateRoomResponse,
  HostChatListSubscribeItem,
  HostChatPostMessageRequest,
  HostChatPostMessageResponse,
  HostChatRegisterBotRequest,
  HostChatRegisterBotResponse,
  HostDevicePermissionRequest,
  HostDevicePermissionResponse,
  HostFeatureSupportedRequest,
  HostFeatureSupportedResponse,
  HostPushNotificationRequest,
  HostPushNotificationResponse,
  HostThemeSubscribeItem,
  RemotePermissionRequest,
  RemotePermissionResponse,
} from "@parity/truapi";
import type { GenericError, NotificationId } from "@parity/truapi";
import {
  AuthState,
  CoreStorageKey,
  HostChainSet,
  ProductContext,
  UserConfirmationReview,
} from "./host-callbacks.js";
import type { RequiredHostCallbacks } from "./host-callbacks.js";

import type { ChainConnect } from "../runtime.js";
import { chainConnectAdapter, driveResultStream } from "../adapter-support.js";

/**
 * Byte-oriented callback surface the WASM core invokes. Members of an
 * optional capability are absent when the host omits the capability;
 * the core then answers the matching product calls with `Unsupported`.
 */
export interface RawCallbacks {
  authStateChanged(state: Uint8Array): void;
  chainConnect: ChainConnect;
  createChatRoom?(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  registerChatBot?(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  postChatMessage?(
    product: Uint8Array,
    request: Uint8Array,
  ): Promise<Uint8Array>;
  subscribeChatRooms?(
    product: Uint8Array,
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  readCoreStorage(key: Uint8Array): Promise<Uint8Array | null | undefined>;
  writeCoreStorage(key: Uint8Array, value: Uint8Array): Promise<void>;
  clearCoreStorage(key: Uint8Array): Promise<void>;
  featureSupported(request: Uint8Array): Promise<Uint8Array>;
  supportedChains(): Promise<Uint8Array>;
  navigateTo(url: string): Promise<void>;
  pushNotification(notification: Uint8Array): Promise<Uint8Array>;
  cancelNotification(id: NotificationId): Promise<void>;
  devicePermission(request: Uint8Array): Promise<Uint8Array>;
  remotePermission(request: Uint8Array): Promise<Uint8Array>;
  lookupPreimage(
    key: Uint8Array,
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  read(key: string): Promise<Uint8Array | null | undefined>;
  write(key: string, value: Uint8Array): Promise<void>;
  clear(key: string): Promise<void>;
  subscribeTheme(
    sendItem: (item?: Uint8Array) => void,
    sendError: (error: GenericError) => void,
  ): (() => void) | void;
  confirmUserAction(review: Uint8Array): Promise<boolean>;
}
/** Adapt typed host callbacks into the raw SCALE callback surface the
 *  WASM core invokes. */
export function createWasmRawCallbacks(
  callbacks: RequiredHostCallbacks,
): RawCallbacks {
  const chat = callbacks.chat;
  return {
    authStateChanged: async (state) =>
      await callbacks.auth.authStateChanged(AuthState.dec(state)),
    chainConnect: chainConnectAdapter(callbacks.chain),
    ...(chat
      ? {
          createChatRoom: async (product, request) =>
            HostChatCreateRoomResponse.enc(
              await chat.createChatRoom(
                ProductContext.dec(product),
                HostChatCreateRoomRequest.dec(request),
              ),
            ),
          registerChatBot: async (product, request) =>
            HostChatRegisterBotResponse.enc(
              await chat.registerChatBot(
                ProductContext.dec(product),
                HostChatRegisterBotRequest.dec(request),
              ),
            ),
          postChatMessage: async (product, request) =>
            HostChatPostMessageResponse.enc(
              await chat.postChatMessage(
                ProductContext.dec(product),
                HostChatPostMessageRequest.dec(request),
              ),
            ),
          subscribeChatRooms: (product, sendItem, sendError) =>
            driveResultStream(
              chat.subscribeChatRooms(ProductContext.dec(product)),
              (item) => sendItem(HostChatListSubscribeItem.enc(item)),
              sendError,
            ),
        }
      : {}),
    readCoreStorage: async (key) =>
      await callbacks.coreStorage.readCoreStorage(CoreStorageKey.dec(key)),
    writeCoreStorage: async (key, value) =>
      await callbacks.coreStorage.writeCoreStorage(
        CoreStorageKey.dec(key),
        value,
      ),
    clearCoreStorage: async (key) =>
      await callbacks.coreStorage.clearCoreStorage(CoreStorageKey.dec(key)),
    featureSupported: async (request) =>
      HostFeatureSupportedResponse.enc(
        await callbacks.features.featureSupported(
          HostFeatureSupportedRequest.dec(request),
        ),
      ),
    supportedChains: async () =>
      HostChainSet.enc(await callbacks.features.supportedChains()),
    navigateTo: async (url) => await callbacks.navigation.navigateTo(url),
    pushNotification: async (notification) =>
      HostPushNotificationResponse.enc(
        await callbacks.notifications.pushNotification(
          HostPushNotificationRequest.dec(notification),
        ),
      ),
    cancelNotification: async (id) =>
      await callbacks.notifications.cancelNotification(id),
    devicePermission: async (request) =>
      HostDevicePermissionResponse.enc(
        await callbacks.permissions.devicePermission(
          HostDevicePermissionRequest.dec(request),
        ),
      ),
    remotePermission: async (request) =>
      RemotePermissionResponse.enc(
        await callbacks.permissions.remotePermission(
          RemotePermissionRequest.dec(request),
        ),
      ),
    lookupPreimage: (key, sendItem, sendError) =>
      driveResultStream(
        callbacks.preimage.lookupPreimage(key),
        sendItem,
        sendError,
      ),
    read: async (key) => await callbacks.productStorage.read(key),
    write: async (key, value) =>
      await callbacks.productStorage.write(key, value),
    clear: async (key) => await callbacks.productStorage.clear(key),
    subscribeTheme: (sendItem, sendError) =>
      driveResultStream(
        callbacks.theme.subscribeTheme(),
        (item) => sendItem(HostThemeSubscribeItem.enc(item)),
        sendError,
      ),
    confirmUserAction: async (review) =>
      await callbacks.userConfirmation.confirmUserAction(
        UserConfirmationReview.dec(review),
      ),
  };
}
