//! Auto-generated by truapi-codegen. Do not edit.
//!
//! Mechanical wasm-bindgen callback bridge derived from
//! `truapi-platform`. Raw callback names and payload shapes match the
//! generated TypeScript host-callback adapter.

use futures::stream::BoxStream;
use js_sys::{Function, Uint8Array};
use parity_scale_codec::Encode;
use truapi::v01;
use wasm_bindgen::JsValue;

use super::{
    WasmPlatform, call_js_function, decode_bytes, decode_js_item, generic, get_function,
    get_optional_function, invoke_bool, invoke_bytes_return, invoke_js_subscription,
    invoke_optional_bytes_return, invoke_unit, missing_callback, parse_optional_bytes_item,
};

/// JS-side callbacks invoked by the wasm platform bridge. Methods with
/// Rust default bodies are still required here because the generated TS
/// adapter resolves optional host callbacks before constructing this
/// raw callback object.
///
/// Callbacks of an optional capability trait are replaced by a throwing
/// stub when the host omits the group. The core never reaches them: it
/// only holds an adapter for a capability whose `has_*` accessor is
/// true, and answers the rest with `Unsupported`.
pub(super) struct JsBridge {
    pub(super) auth_state_changed: Function,
    pub(super) chain_connect: Function,
    pub(super) create_chat_room: Function,
    pub(super) register_chat_bot: Function,
    pub(super) post_chat_message: Function,
    pub(super) subscribe_chat_rooms: Function,
    pub(super) read_core_storage: Function,
    pub(super) write_core_storage: Function,
    pub(super) clear_core_storage: Function,
    pub(super) feature_supported: Function,
    pub(super) supported_chains: Function,
    pub(super) navigate_to: Function,
    pub(super) push_notification: Function,
    pub(super) cancel_notification: Function,
    pub(super) device_permission_status: Function,
    pub(super) device_permission: Function,
    pub(super) remote_permission: Function,
    pub(super) lookup_preimage: Function,
    pub(super) read: Function,
    pub(super) write: Function,
    pub(super) clear: Function,
    pub(super) subscribe_theme: Function,
    pub(super) confirm_user_action: Function,
    pub(super) chat_present: bool,
    pub(super) permission_status_present: bool,
}

impl JsBridge {
    pub(super) fn from_js(callbacks: &JsValue) -> Result<Self, JsValue> {
        Ok(Self {
            auth_state_changed: get_function(callbacks, "authStateChanged")?,
            chain_connect: get_function(callbacks, "chainConnect")?,
            create_chat_room: get_optional_function(callbacks, "createChatRoom")?
                .unwrap_or_else(|| missing_callback("createChatRoom")),
            register_chat_bot: get_optional_function(callbacks, "registerChatBot")?
                .unwrap_or_else(|| missing_callback("registerChatBot")),
            post_chat_message: get_optional_function(callbacks, "postChatMessage")?
                .unwrap_or_else(|| missing_callback("postChatMessage")),
            subscribe_chat_rooms: get_optional_function(callbacks, "subscribeChatRooms")?
                .unwrap_or_else(|| missing_callback("subscribeChatRooms")),
            read_core_storage: get_function(callbacks, "readCoreStorage")?,
            write_core_storage: get_function(callbacks, "writeCoreStorage")?,
            clear_core_storage: get_function(callbacks, "clearCoreStorage")?,
            feature_supported: get_function(callbacks, "featureSupported")?,
            supported_chains: get_function(callbacks, "supportedChains")?,
            navigate_to: get_function(callbacks, "navigateTo")?,
            push_notification: get_function(callbacks, "pushNotification")?,
            cancel_notification: get_function(callbacks, "cancelNotification")?,
            device_permission_status: get_optional_function(callbacks, "devicePermissionStatus")?
                .unwrap_or_else(|| missing_callback("devicePermissionStatus")),
            device_permission: get_function(callbacks, "devicePermission")?,
            remote_permission: get_function(callbacks, "remotePermission")?,
            lookup_preimage: get_function(callbacks, "lookupPreimage")?,
            read: get_function(callbacks, "read")?,
            write: get_function(callbacks, "write")?,
            clear: get_function(callbacks, "clear")?,
            subscribe_theme: get_function(callbacks, "subscribeTheme")?,
            confirm_user_action: get_function(callbacks, "confirmUserAction")?,
            chat_present: get_optional_function(callbacks, "createChatRoom")?.is_some()
                && get_optional_function(callbacks, "registerChatBot")?.is_some()
                && get_optional_function(callbacks, "postChatMessage")?.is_some()
                && get_optional_function(callbacks, "subscribeChatRooms")?.is_some(),
            permission_status_present: get_optional_function(callbacks, "devicePermissionStatus")?
                .is_some(),
        })
    }

    /// Whether the host supplied every `chat` callback.
    pub(super) fn has_chat(&self) -> bool {
        self.chat_present
    }

    /// Whether the host supplied every `permission_status` callback.
    pub(super) fn has_permission_status(&self) -> bool {
        self.permission_status_present
    }
}

impl truapi_platform::AuthPresenter for WasmPlatform {
    fn auth_state_changed(&self, state: truapi_platform::AuthState) {
        if let Err(reason) = call_js_function(
            &self.bridge.auth_state_changed,
            &vec![Uint8Array::from(state.encode().as_slice()).into()],
        ) {
            web_sys::console::error_1(&JsValue::from_str(&reason));
        }
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::ChatPlatform for WasmPlatform {
    async fn create_chat_room(
        &self,
        product: &truapi_platform::ProductContext,
        request: v01::HostChatCreateRoomRequest,
    ) -> Result<v01::HostChatCreateRoomResponse, v01::HostChatCreateRoomError> {
        let bytes = invoke_bytes_return(
            &self.bridge.create_chat_room,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| v01::HostChatCreateRoomError::Unknown { reason })?;
        decode_bytes::<v01::HostChatCreateRoomResponse>(
            bytes,
            "createChatRoom response did not decode",
        )
        .map_err(|reason| v01::HostChatCreateRoomError::Unknown { reason })
    }

    async fn register_chat_bot(
        &self,
        product: &truapi_platform::ProductContext,
        request: v01::HostChatRegisterBotRequest,
    ) -> Result<v01::HostChatRegisterBotResponse, v01::HostChatRegisterBotError> {
        let bytes = invoke_bytes_return(
            &self.bridge.register_chat_bot,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| v01::HostChatRegisterBotError::Unknown { reason })?;
        decode_bytes::<v01::HostChatRegisterBotResponse>(
            bytes,
            "registerChatBot response did not decode",
        )
        .map_err(|reason| v01::HostChatRegisterBotError::Unknown { reason })
    }

    async fn post_chat_message(
        &self,
        product: &truapi_platform::ProductContext,
        request: v01::HostChatPostMessageRequest,
    ) -> Result<v01::HostChatPostMessageResponse, v01::HostChatPostMessageError> {
        let bytes = invoke_bytes_return(
            &self.bridge.post_chat_message,
            vec![
                Uint8Array::from(product.encode().as_slice()).into(),
                Uint8Array::from(request.encode().as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| v01::HostChatPostMessageError::Unknown { reason })?;
        decode_bytes::<v01::HostChatPostMessageResponse>(
            bytes,
            "postChatMessage response did not decode",
        )
        .map_err(|reason| v01::HostChatPostMessageError::Unknown { reason })
    }

    fn subscribe_chat_rooms(
        &self,
        product: &truapi_platform::ProductContext,
    ) -> BoxStream<'static, Result<v01::HostChatListSubscribeItem, v01::GenericError>> {
        invoke_js_subscription(
            &self.bridge.subscribe_chat_rooms,
            Some(product.encode()),
            parse_host_chat_list_subscribe_item_item,
        )
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::CoreStorage for WasmPlatform {
    async fn read_core_storage(
        &self,
        key: truapi_platform::CoreStorageKey,
    ) -> Result<Option<Vec<u8>>, v01::GenericError> {
        invoke_optional_bytes_return(
            &self.bridge.read_core_storage,
            vec![Uint8Array::from(key.encode().as_slice()).into()],
            "readCoreStorage must resolve to Uint8Array, null or undefined",
        )
        .await
        .map_err(generic)
    }

    async fn write_core_storage(
        &self,
        key: truapi_platform::CoreStorageKey,
        value: Vec<u8>,
    ) -> Result<(), v01::GenericError> {
        invoke_unit(
            &self.bridge.write_core_storage,
            vec![
                Uint8Array::from(key.encode().as_slice()).into(),
                Uint8Array::from(value.as_slice()).into(),
            ],
        )
        .await
        .map_err(generic)
    }

    async fn clear_core_storage(
        &self,
        key: truapi_platform::CoreStorageKey,
    ) -> Result<(), v01::GenericError> {
        invoke_unit(
            &self.bridge.clear_core_storage,
            vec![Uint8Array::from(key.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::Features for WasmPlatform {
    async fn feature_supported(
        &self,
        request: v01::HostFeatureSupportedRequest,
    ) -> Result<v01::HostFeatureSupportedResponse, v01::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.feature_supported,
            vec![Uint8Array::from(request.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<v01::HostFeatureSupportedResponse>(
            bytes,
            "featureSupported response did not decode",
        )
        .map_err(generic)
    }

    async fn supported_chains(&self) -> Result<truapi_platform::HostChainSet, v01::GenericError> {
        let bytes = invoke_bytes_return(&self.bridge.supported_chains, Vec::new())
            .await
            .map_err(generic)?;
        decode_bytes::<truapi_platform::HostChainSet>(
            bytes,
            "supportedChains response did not decode",
        )
        .map_err(generic)
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::Navigation for WasmPlatform {
    async fn navigate_to(&self, url: String) -> Result<(), v01::HostNavigateToError> {
        invoke_unit(&self.bridge.navigate_to, vec![JsValue::from_str(&url)])
            .await
            .map_err(|reason| v01::HostNavigateToError::Unknown { reason })
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::Notifications for WasmPlatform {
    async fn push_notification(
        &self,
        notification: v01::HostPushNotificationRequest,
    ) -> Result<v01::HostPushNotificationResponse, v01::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.push_notification,
            vec![Uint8Array::from(notification.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<v01::HostPushNotificationResponse>(
            bytes,
            "pushNotification response did not decode",
        )
        .map_err(generic)
    }

    async fn cancel_notification(&self, id: v01::NotificationId) -> Result<(), v01::GenericError> {
        invoke_unit(
            &self.bridge.cancel_notification,
            vec![JsValue::from_f64(f64::from(id))],
        )
        .await
        .map_err(generic)
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::PermissionStatusHost for WasmPlatform {
    async fn device_permission_status(
        &self,
        request: v01::HostDevicePermissionRequest,
    ) -> Result<truapi_platform::DevicePermissionStatus, v01::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.device_permission_status,
            vec![Uint8Array::from(request.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<truapi_platform::DevicePermissionStatus>(
            bytes,
            "devicePermissionStatus response did not decode",
        )
        .map_err(generic)
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::Permissions for WasmPlatform {
    async fn device_permission(
        &self,
        request: v01::HostDevicePermissionRequest,
    ) -> Result<v01::HostDevicePermissionResponse, v01::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.device_permission,
            vec![Uint8Array::from(request.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<v01::HostDevicePermissionResponse>(
            bytes,
            "devicePermission response did not decode",
        )
        .map_err(generic)
    }

    async fn remote_permission(
        &self,
        request: v01::RemotePermissionRequest,
    ) -> Result<v01::RemotePermissionResponse, v01::GenericError> {
        let bytes = invoke_bytes_return(
            &self.bridge.remote_permission,
            vec![Uint8Array::from(request.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)?;
        decode_bytes::<v01::RemotePermissionResponse>(
            bytes,
            "remotePermission response did not decode",
        )
        .map_err(generic)
    }
}

impl truapi_platform::PreimageHost for WasmPlatform {
    fn lookup_preimage(
        &self,
        key: Vec<u8>,
    ) -> BoxStream<'static, Result<Option<Vec<u8>>, v01::GenericError>> {
        invoke_js_subscription(
            &self.bridge.lookup_preimage,
            Some(key),
            parse_optional_bytes_item,
        )
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::ProductStorage for WasmPlatform {
    async fn read(&self, key: String) -> Result<Option<Vec<u8>>, v01::HostLocalStorageReadError> {
        invoke_optional_bytes_return(
            &self.bridge.read,
            vec![JsValue::from_str(&key)],
            "read must resolve to Uint8Array, null or undefined",
        )
        .await
        .map_err(|reason| v01::HostLocalStorageReadError::Unknown { reason })
    }

    async fn write(
        &self,
        key: String,
        value: Vec<u8>,
    ) -> Result<(), v01::HostLocalStorageReadError> {
        invoke_unit(
            &self.bridge.write,
            vec![
                JsValue::from_str(&key),
                Uint8Array::from(value.as_slice()).into(),
            ],
        )
        .await
        .map_err(|reason| v01::HostLocalStorageReadError::Unknown { reason })
    }

    async fn clear(&self, key: String) -> Result<(), v01::HostLocalStorageReadError> {
        invoke_unit(&self.bridge.clear, vec![JsValue::from_str(&key)])
            .await
            .map_err(|reason| v01::HostLocalStorageReadError::Unknown { reason })
    }
}

impl truapi_platform::ThemeHost for WasmPlatform {
    fn subscribe_theme(
        &self,
    ) -> BoxStream<'static, Result<v01::HostThemeSubscribeItem, v01::GenericError>> {
        invoke_js_subscription(
            &self.bridge.subscribe_theme,
            None,
            parse_host_theme_subscribe_item_item,
        )
    }
}

#[truapi_platform::async_trait]
impl truapi_platform::UserConfirmation for WasmPlatform {
    async fn confirm_user_action(
        &self,
        review: truapi_platform::UserConfirmationReview,
    ) -> Result<bool, v01::GenericError> {
        invoke_bool(
            &self.bridge.confirm_user_action,
            vec![Uint8Array::from(review.encode().as_slice()).into()],
        )
        .await
        .map_err(generic)
    }
}

fn parse_host_chat_list_subscribe_item_item(
    value: JsValue,
) -> Result<v01::HostChatListSubscribeItem, String> {
    decode_js_item::<v01::HostChatListSubscribeItem>(value, "HostChatListSubscribeItem")
}

fn parse_host_theme_subscribe_item_item(
    value: JsValue,
) -> Result<v01::HostThemeSubscribeItem, String> {
    decode_js_item::<v01::HostThemeSubscribeItem>(value, "HostThemeSubscribeItem")
}
