// Auto-generated by truapi-codegen. Do not edit.
//
// Worker-side metadata and proxy functions for the raw WASM callback
// surface. The worker transport/lifecycle remains hand-written; this
// file owns the callback names, host-hook arity, and
// subscription payload shape derived from `truapi-platform`.

import type { RawCallbacks } from "./host-callbacks-adapter.js";
import type { GenericError } from "@parity/truapi";

import type { ChainConnect } from "../runtime.js";

export const CALLBACK_NAMES = [
  "authStateChanged",
  "createChatRoom",
  "registerChatBot",
  "postChatMessage",
  "readCoreStorage",
  "writeCoreStorage",
  "clearCoreStorage",
  "featureSupported",
  "supportedChains",
  "navigateTo",
  "pushNotification",
  "cancelNotification",
  "devicePermission",
  "remotePermission",
  "read",
  "write",
  "clear",
  "confirmUserAction",
] as const;
export type CallbackName = (typeof CALLBACK_NAMES)[number];

export const SUBSCRIPTION_NAMES = [
  "subscribeChatRooms",
  "lookupPreimage",
  "subscribeTheme",
] as const;
export type SubscriptionName = (typeof SUBSCRIPTION_NAMES)[number];

export interface WorkerCallbackBridge {
  callbackRequest(
    name: CallbackName,
    args: readonly unknown[],
  ): Promise<unknown>;
  startSubscription<T>(
    name: SubscriptionName,
    payload: Uint8Array | null,
    sendItem: (value: T) => void,
    sendError: (error: GenericError) => void,
  ): () => void;
  chainConnect: ChainConnect;
}

function rawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<
  Pick<
    RawCallbacks,
    | "authStateChanged"
    | "readCoreStorage"
    | "writeCoreStorage"
    | "clearCoreStorage"
    | "featureSupported"
    | "supportedChains"
    | "navigateTo"
    | "pushNotification"
    | "cancelNotification"
    | "devicePermission"
    | "remotePermission"
    | "read"
    | "write"
    | "clear"
    | "confirmUserAction"
  >
> {
  return {
    authStateChanged: (state) =>
      void bridge.callbackRequest("authStateChanged", [state]).catch(() => {}),
    readCoreStorage: (key) =>
      bridge.callbackRequest("readCoreStorage", [key]) as ReturnType<
        Required<RawCallbacks>["readCoreStorage"]
      >,
    writeCoreStorage: (key, value) =>
      bridge.callbackRequest("writeCoreStorage", [key, value]) as ReturnType<
        Required<RawCallbacks>["writeCoreStorage"]
      >,
    clearCoreStorage: (key) =>
      bridge.callbackRequest("clearCoreStorage", [key]) as ReturnType<
        Required<RawCallbacks>["clearCoreStorage"]
      >,
    featureSupported: (request) =>
      bridge.callbackRequest("featureSupported", [request]) as ReturnType<
        Required<RawCallbacks>["featureSupported"]
      >,
    supportedChains: () =>
      bridge.callbackRequest("supportedChains", []) as ReturnType<
        Required<RawCallbacks>["supportedChains"]
      >,
    navigateTo: (url) =>
      bridge.callbackRequest("navigateTo", [url]) as ReturnType<
        Required<RawCallbacks>["navigateTo"]
      >,
    pushNotification: (notification) =>
      bridge.callbackRequest("pushNotification", [notification]) as ReturnType<
        Required<RawCallbacks>["pushNotification"]
      >,
    cancelNotification: (id) =>
      bridge.callbackRequest("cancelNotification", [id]) as ReturnType<
        Required<RawCallbacks>["cancelNotification"]
      >,
    devicePermission: (request) =>
      bridge.callbackRequest("devicePermission", [request]) as ReturnType<
        Required<RawCallbacks>["devicePermission"]
      >,
    remotePermission: (request) =>
      bridge.callbackRequest("remotePermission", [request]) as ReturnType<
        Required<RawCallbacks>["remotePermission"]
      >,
    read: (key) =>
      bridge.callbackRequest("read", [key]) as ReturnType<
        Required<RawCallbacks>["read"]
      >,
    write: (key, value) =>
      bridge.callbackRequest("write", [key, value]) as ReturnType<
        Required<RawCallbacks>["write"]
      >,
    clear: (key) =>
      bridge.callbackRequest("clear", [key]) as ReturnType<
        Required<RawCallbacks>["clear"]
      >,
    confirmUserAction: (review) =>
      bridge.callbackRequest("confirmUserAction", [review]) as ReturnType<
        Required<RawCallbacks>["confirmUserAction"]
      >,
  };
}

function subscriptionRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<Pick<RawCallbacks, "lookupPreimage" | "subscribeTheme">> {
  return {
    lookupPreimage: (key, sendItem, sendError) =>
      bridge.startSubscription("lookupPreimage", key, sendItem, sendError),
    subscribeTheme: (sendItem, sendError) =>
      bridge.startSubscription("subscribeTheme", null, sendItem, sendError),
  };
}

function chatRawCallbacks(
  bridge: WorkerCallbackBridge,
): Required<
  Pick<
    RawCallbacks,
    | "createChatRoom"
    | "registerChatBot"
    | "postChatMessage"
    | "subscribeChatRooms"
  >
> {
  return {
    createChatRoom: (product, request) =>
      bridge.callbackRequest("createChatRoom", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["createChatRoom"]>,
    registerChatBot: (product, request) =>
      bridge.callbackRequest("registerChatBot", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["registerChatBot"]>,
    postChatMessage: (product, request) =>
      bridge.callbackRequest("postChatMessage", [
        product,
        request,
      ]) as ReturnType<Required<RawCallbacks>["postChatMessage"]>,
    subscribeChatRooms: (product, sendItem, sendError) =>
      bridge.startSubscription(
        "subscribeChatRooms",
        product,
        sendItem,
        sendError,
      ),
  };
}

/**
 * Optional capabilities the main-thread host actually serves. A
 * capability left out here is not proxied into the worker, so the
 * core answers its product calls with `Unsupported`.
 */
export interface OptionalCapabilities {
  /** Whether the host serves this capability. */
  chat?: boolean;
}

export function createWorkerRawCallbacks(
  bridge: WorkerCallbackBridge,
  capabilities: OptionalCapabilities = {},
): Record<string, unknown> {
  const callbacks: Record<string, unknown> = {
    ...rawCallbacks(bridge),
    ...subscriptionRawCallbacks(bridge),
    chainConnect: bridge.chainConnect,
  };
  if (capabilities.chat) Object.assign(callbacks, chatRawCallbacks(bridge));
  return callbacks;
}

export function startRawSubscription(
  callbacks: RawCallbacks,
  name: SubscriptionName,
  payload: Uint8Array | null,
  sendItem: (value?: unknown) => void,
  sendError: (error: GenericError) => void,
): (() => void) | void {
  switch (name) {
    case "subscribeChatRooms":
      if (payload === null) {
        console.warn(`[truapi worker] ${name} requires payload`);
        return undefined;
      }
      return callbacks.subscribeChatRooms?.(payload, sendItem, sendError);
    case "lookupPreimage":
      if (payload === null) {
        console.warn(`[truapi worker] ${name} requires payload`);
        return undefined;
      }
      return callbacks.lookupPreimage(payload, sendItem, sendError);
    case "subscribeTheme":
      return callbacks.subscribeTheme(sendItem, sendError);
  }
}
